### ISSUE TITLE
text box is too small

### ISSUE THREAD

**Issue by Ruchian** [CreativeMD/PlayerRevive#10]
Hi, can you do something about the text box?
Every time I try to type and send something to my mate while being dead I notice that the amount of text I can type per line is very limited, and also I'd often crash because, at least this is what I think happens, I can type more inside the text box than the text box can handle.

example of the crash result:
``Description: Rendering screen

java.lang.StringIndexOutOfBoundsException: String index out of range: -3``

It would be nice if I could send just as much text as a regular minecraft chat message.

edit notice: (I fixed a few typos and hopefully made my message friendlier and clearer. xd)

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report?

**Comment by Ruchian** [comment]
Here.
[crash-2018-02-28_21.55.39-client.txt](https://github.com/CreativeMD/PlayerRevive/files/1776497/crash-2018-02-28_21.55.39-client.txt)

**Comment by CreativeMD** [comment]
Does this fixes it?
https://www.dropbox.com/s/suwqp0ie9p0ohb6/CreativeCore_v1.9.20_mc1.12.2.jar?dl=1

**Comment by Ruchian** [comment]
Unfortunately, it does not.
The crash report looks similar. A noticable difference is though:
`` 	| UCHIJA | creativecore             | 1.9.9                | CreativeCore_v1.9.20_mc1.12.2.jar  ``

here:
![sampleoftheproblem](https://user-images.githubusercontent.com/24900404/37035229-26f944ee-214c-11e8-9f38-35d5602ecb3d.png)

I tried typing "There can go way more text here..." but as you can see it didn't work out very well.
If I press press enter there, I crash.
Here's a new crash report by the way.

[crash-2018-03-06_14.39.29-client.txt](https://github.com/CreativeMD/PlayerRevive/files/1785199/crash-2018-03-06_14.39.29-client.txt)

(I tested it in a small server by myself) fml-server-latest doesn't give any useful hints.
fml-client-latest also has nothing.
I don't see any trace/debug entries related to playerrevive nor creativecore.
(basically even the client's log cannot tell what I was trying to send, even though I have screenshot evidence.)

**Comment by CreativeMD** [comment]
Fixed it in the newest version of PlayerRevive. Sorry that it took me so long. Thanks for reporting this issue!
