### ISSUE TITLE
die by reviving

### ISSUE THREAD

**Issue by Lionn02** [CreativeMD/PlayerRevive#100]
When I give up or get finished off and hit respawn I die instantly and every time I have to log out of the server and log back in for it to fix itself

**Comment by CreativeMD** [comment]
I need more context. What minecraft version are you using? There is an issue with magma and mohist unfortunately PlayerRevive is not compatible with them.

**Comment by BluPapu** [comment]
same, i use 1.16.5

**Comment by CreativeMD** [comment]
Unfortunately things don't work in 1.16 with magma and mohist.
