### ISSUE TITLE
Issue when using First Aid (1.18.2)

### ISSUE THREAD

**Issue by PakoJones88** [CreativeMD/PlayerRevive#101]
Hi. When I use your mod along with First Aid and I'm knocked down, the chat doesn't display the "X is bleeding..." message. And after I completely die, the death message is displayed two times.

These are the jar files I was using:
![image](https://user-images.githubusercontent.com/110305970/182408128-c180b611-3ede-442d-b7ef-71904ea952d4.png)

**Comment by CreativeMD** [comment]
The bleeding message can be enabled or disabled. Use the command /cmdconfig to check if it got disabled. Furthermore this seems like a minor issue, which will most likely be fixed in 1.19. So I will close this issue for now.
