### ISSUE TITLE
Compatibility with travelers backpack

### ISSUE THREAD

**Issue by Midnight-GHub** [CreativeMD/PlayerRevive#103]
**Description of the issue** -
The mod 'Travelers backpack' adds backpacks with certain abilities to the game. The creeper backpack adds the ability to cause explosion and gives potion effects (regeneration, resistance and fire resistance) when you are about to die. The issue is that you get knocked out before the ability activates which makes this ability useless.

**Solution** -
Making the ability activate before getting knocked out would fix the issue.

**Versions** - 
Minecraft 1.18.2
PlayerRevive_FORGE_v2.0.1_mc1.18.2
TravelersBackpack-1.18.2-7.1.8

**Comment by CreativeMD** [comment]
I cannot fix this from my end. Ask Travelers backpack if they want to change it. Sorry, can't help you there.
