### ISSUE TITLE
Crash when you die

### ISSUE THREAD

**Issue by Wysam96** [CreativeMD/PlayerRevive#104]
Hello, yesterday I sent you a query because the surrender button was not working, I followed your instructions and updated, but now the server crashes when someone dies

Minecraft version: 1.19
Forge version: 41.1.0

Crash report
https://pastebin.com/BgwxMiL3

**Comment by CreativeMD** [comment]
You are using the newest version for 1.19.1 for 1.19. Either go back to the latest version for 1.19 or update your minecraft to 1.19.1

**Comment by Wysam96** [comment]
I couldn't write this message before, sorry for the delay.
With version 2.0.6 on the server and version 2.0.7 on the clients there is no crash and the error of not being able to give up is solved
