### ISSUE TITLE
issue with the bleading state

### ISSUE THREAD

**Issue by AdriftWoltf** [CreativeMD/PlayerRevive#109]
I create a event in minecraft to play with my friends in a zombi apocalypse with pvp etc. but when you get down a player you can not kill him you need to whait the timer go down.

We use the moguns if the issue is caused by this mod.

**Comment by CreativeMD** [comment]
What version of the mod are you using? Because in the newer version a player can be killed when bleeding?

**Comment by CreativeMD** [comment]
I will close this issue for now. If this issue still persists post the requested information here.
