### ISSUE TITLE
2 Openblock Graves on Death

### ISSUE THREAD

**Issue by Charismara** [CreativeMD/PlayerRevive#11]
Minecraft: 1.12.2
Forge: 14.23.2.26.24
OpenBlocks: 1.7.6
PlayerRevive: 1.2.11

If someone die OpenBlocks spawn a gravestone without any Items and if he doesn't get revived a second gravestone with his Items spawn. 

Is there a way to remove the first gravestone?

**Comment by CreativeMD** [comment]
Can you try if this version works? https://www.dropbox.com/s/ctl59zlwjcu8nks/PlayerRevive_v1.2.12_mc1.12.2.jar?dl=1

**Comment by Charismara** [comment]
It work 😄 thank you

**Comment by CreativeMD** [comment]
Nice, uploaded it to curseforge, new version should be available soon. Thanks for reporting this issue!
