### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Looodon** [CreativeMD/PlayerRevive#110]
Hey,
This isn't an issue, more a feature request if that's okay. I was wondering if you'd be interested to add two features:
-to disable /kill in creative triggering the downed function (so the mod doesn't trigger during creative)
-an option to lower the left click count down when downed, cuz the wait time feels long when doing tasks that require constant death
Thank you so much! :)

**Comment by CreativeMD** [comment]
Added in the newest version. Thanks for your suggestions!
