### ISSUE TITLE
Player Revive bugged in Mohist?

### ISSUE THREAD

**Issue by SrChuleta** [CreativeMD/PlayerRevive#111]
Hi!
I´ve experienced a bug with this mod when i tried to add it to a mohist server in 1.16.5 version. I tried it in Aternos, but when im supposed to die, a death message appears, but im alive, and im inmortal unless i type /kill. It doesnt work either in a dedicated server i own, in that server, when somebody dies, if they respawn, the die again instantly.

**Comment by CreativeMD** [comment]
This is a known bug and unfortunately cannot be fixed. It might work in 1.18 though. Sorry, can't help you there.
