### ISSUE TITLE
1.18.2 revival skip

### ISSUE THREAD

**Issue by GreenForzeGaming** [CreativeMD/PlayerRevive#112]
logging out during the timer when youre dying, you can log out and in and youre alive again.

**Comment by CreativeMD** [comment]
This is probably caused by another mod. Or you using mohist or magma? What other mods do you have installed?

**Comment by GreenForzeGaming** [comment]
![image](https://user-images.githubusercontent.com/62345403/195062109-0d756ca7-4ffe-4e46-96f2-de34ae583020.png)

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I don't see any obvious problematic mod. Are you using mohist or magma?

**Comment by GreenForzeGaming** [comment]
Nope none of those

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CreativeMD** [comment]
Ok, then I see no other option than to remove half of the mods and see the issue still persists. If yes remove even more mods, till it works. Once it works you know what mods could have caused it and try them out. It can take a while, but I don't see a different way to figure out what mod is causing the problem. You could try to just install just CreativeCore and PlayerRevive and see if it works then (before trying out the other stuff).

**Comment by GreenForzeGaming** [comment]
I remade my mod pack and it still keeps me alive after relogging

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by GreenForzeGaming** [comment]
idk what is going on but whenever i "die" my health gets put at 5 hearts and after restart im alive again
