### ISSUE TITLE
Instant Respawn

### ISSUE THREAD

**Issue by thedeerirty** [CreativeMD/PlayerRevive#113]
Not sure what's doing this. 

The mods that come to mind are the Rally Health Mod, First Aid, or Vampirism, but I'm positive you've got compact with the latter. Fairly sure it isn't the first either tbh.

The issue is: when a player dies, and isn't revived, they aren't... "dead", on the respawn screen. and when they hit the respawn button, they're in the same same place. If they have normal heart displace toggle with First Aid, they show the same health they died at, but their entire body's health is 0. If hit again, they'll go down and repeat the process again (although now mobs still aggro them)

It counts as a death, as it triggers spawns for gravestone mods like Tombstone, oddly enough. Any idea of what a mod what need to affect to mess with this? I can't think of anything on my list that changes player death, save maybe. Idk something mana and artifice does? spitballing here.

**Comment by Sember225** [comment]
I also have this issue, I only have First Aid. Testing now without it.

**Comment by CreativeMD** [comment]
This is most likely a conflict with the First Aid mod. There is an open issue https://github.com/ichttt/FirstAid/issues/180#issuecomment-1278339767. Let's hope it will be fixed soon.

**Comment by CreativeMD** [comment]
Is this still an issue in 1.19.3?

**Comment by CreativeMD** [comment]
I will close this issue for now. If someone could retest this for 1.19.4 and post it here would be great.

**Comment by Sember225** [comment]
Still in 1.18.2 here, I have some additional information. 
In a server environment, using First Aid and Player Revive. 
When a player dies they are downed as they should be. If the player waits a minute and expires naturally, they'll respawn at their spawn no issue. 

The only time this issue occurs is when the player "gives up", they will spawn back at the exact point of giving up. This leads me to believe it's a player revive issue, not I'm not too versed in these things.

**Comment by Sember225** [comment]
On a brand new instance, 1.19.4, FORGE 45.2.0
CreativeCore_FORGE_v2.10.22
PlayerRevive_FORGE_v2.0.16
FirstAid 1.14.0

Giving up now acts as it should, killing the player and sending them to their spawn point. Really hoping for a port of this fix for 1.18.2.

**Comment by CreativeMD** [comment]
Cannot do anything there at the moment. The author of FirstAid unfortunately has not responded yet. Furthermore I do not support 1.18.2 anymore. So my fix would be only for 1.20.1.
