### ISSUE TITLE
1.18.2 revival skip Incompatibility with Spice of Life Sweet Potato

### ISSUE THREAD

**Issue by GreenForzeGaming** [CreativeMD/PlayerRevive#114]
you can delete the old one.
i figured oiut what mod causes this and this is it 
https://www.curseforge.com/minecraft/mc-mods/spice-of-life-sweet-potato-edition

**Comment by CreativeMD** [comment]
Why not post your results in the other issue? (Please do so next time).
I have reported this issue to Spice of Life Sweet Potato Edition. Let's hope it can be figured out soon. Would be cool if you can join the conversation and help testing.
https://github.com/tarinoita/Spice-of-Life-Sweet-Potato/issues/14

**Comment by CreativeMD** [comment]
I will close this issue now. I have dropped support for 1.18.2 and there is nothing I can do about it anyway.
