### ISSUE TITLE
First Aid, Bandages are not working after beeing revived by someone.

### ISSUE THREAD

**Issue by Boract** [CreativeMD/PlayerRevive#117]
Hello, I've got a little problem with the First Aid and Player Revive mod. After reviving someone, the bandages of First Aid are not working The first aid interface becomes grey and when I applly a bandage it stays at 18 seconds remain for the healing timer. I think the issue comes from Player Revive 'cause before dying and beeing revived by someone everything about the bandages works.

**Comment by Boract** [comment]
I play in 1.16.5 with the 500K downloaded version of Player Revive. First Aid 1.9.8 and 2.2.1 1.16.5 Creative Core.

**Comment by CreativeMD** [comment]
Sorry, but I have dropped support for 1.16.5 a long time ago. Cannot help you there :| unfortunately.
