### ISSUE TITLE
MC 1.20 crash 

### ISSUE THREAD

**Issue by Devilswarchild** [CreativeMD/PlayerRevive#118]
this mod is asking for fml 47 on base version of mc 1.20 which is only on javafml 46

here is a screenshot and logs

**Comment by Devilswarchild** [comment]
[crash-2023-06-21_15.23.53-fml.txt](https://github.com/CreativeMD/PlayerRevive/files/11824590/crash-2023-06-21_15.23.53-fml.txt)

[debug.log](https://github.com/CreativeMD/PlayerRevive/files/11824603/debug.log)

[latest.log](https://github.com/CreativeMD/PlayerRevive/files/11824605/latest.log)

[launcher_log.txt](https://github.com/CreativeMD/PlayerRevive/files/11824607/launcher_log.txt)

![Screenshot_2](https://github.com/CreativeMD/PlayerRevive/assets/27385258/be9f6e4f-b7ba-4e45-8f0a-8932406b5893)

**Comment by CreativeMD** [comment]
Can you update to 1.20.1? Should be no issue. Normally it should be compatible with 1.20 as well, but I accidentally put FML 47 as a requirement. I can change it if it is really necessary. Just let me know.

**Comment by Devilswarchild** [comment]
yes please that would be ever so helpful. trying to keep my modpacks nice and stable

**Comment by CreativeMD** [comment]
You should use 1.20.1 if possible, because it does not change anything, but it has some critical bug fixes. Please don't stay on 1.20 ... will upload a new version in a few minutes anyway.

**Comment by Devilswarchild** [comment]
ok thank you. and I will keep that in mind
