### ISSUE TITLE
error in common_setup

### ISSUE THREAD

**Issue by JonhXSZ** [CreativeMD/PlayerRevive#119]
[crash-2023-06-26_00.32.22-fml.txt](https://github.com/CreativeMD/PlayerRevive/files/11861252/crash-2023-06-26_00.32.22-fml.txt)
image:
![image](https://github.com/CreativeMD/PlayerRevive/assets/137734376/f789d4a7-8a4d-45d4-87e7-206d91470223)

Version:  1.18.2

[latest.log](https://github.com/CreativeMD/PlayerRevive/files/11861290/latest.log)

**Comment by JonhXSZ** [comment]
i need help pls

**Comment by CreativeMD** [comment]
Update CreativeCore, your version is outdated.
