### ISSUE TITLE
Player get Kicked on her Death

### ISSUE THREAD

**Issue by Charismara** [CreativeMD/PlayerRevive#12]
Minecraft: 1.12.2
Forge: 14.23.2.2624
PlayerRevive: 1.2.11

If a Player die he get kicked from the Server with a "Internal server error" message. And they can't connect anymore. They have to restart Mincraft to connect again.

Here is my [Serverlog](https://pastebin.com/sATcaa25).
Here is their [Clientlog](https://pastebin.com/57Bh654X).

**Comment by CreativeMD** [comment]
Can you try it without any other mods installed? My guess it's an incompatibility with another mod.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. Just reopen if the issue still persists.
