### ISSUE TITLE
player revive bug?

### ISSUE THREAD

**Issue by sukeplayer** [CreativeMD/PlayerRevive#120]
im creating a server on 1.16.5, mohist mods and plugins, when a player dies without being rescued or decides to kill himself and he revives, he falls

https://github.com/CreativeMD/PlayerRevive/assets/138123333/cdd5a4a6-d034-4b33-89c6-b97f2c5e7022

 a death loop and is not fixed until he enters the server again... any solution?

**Comment by CreativeMD** [comment]
Sorry, update Minecraft. I do not support 1.16 anymore. Furthermore this bug was never fixed for this version. It works in 1.19 and 1.20 (I think) and it might even work for 1.18.

**Comment by sukeplayer** [comment]
> Sorry, update Minecraft. I do not support 1.16 anymore. Furthermore this bug was never fixed for this version. It works in 1.19 and 1.20 (I think) and it might even work for 1.18.

oh ok!! thanks for answering as well. :D
