### ISSUE TITLE
The character swims in death

### ISSUE THREAD

**Issue by BlackAures1** [CreativeMD/PlayerRevive#122]
[Modpack](https://www.curseforge.com/minecraft/modpacks/play-as-dragon-gothic-edition)
PlayerRevive_FORGE_v2.0.14_mc1.19.2.jar

My character starts swimming instead of lying still and waiting for respawn. The character can move around.

![2023-07-06_23 56 56](https://github.com/CreativeMD/PlayerRevive/assets/43911230/bcae8eb9-ceb8-4cf9-a79b-741227db9472)

**Comment by CreativeMD** [comment]
Actually you are supposed to move around. That is intentional. It uses the same animation when a player is pushed to the ground. I guess I can close this issue. You can use /cmdconfig and increase the slowness effect to stop the player from moving around. Sorry for responding that late.

**Comment by BlackAures1** [comment]
Okay, it just seemed like a bug rather than a planned feature.
