### ISSUE TITLE
Bug inmortality and blocked inventory

### ISSUE THREAD

**Issue by carlosr9** [CreativeMD/PlayerRevive#126]
Hello! The problem is that, rarely, when I die the character is left in a state of immortality, shaking and unable to open the inventory. It seems to happen with the /kill command or when a player dies while being revived. The only solution I have found is to delete the player data completely. 

By the way, this is version Forge 1.19.2. The file is the last one published for this version.

https://github.com/CreativeMD/PlayerRevive/assets/113271724/74e8cc4a-511c-4ff1-ba5c-477fd3a2bb50

**Comment by CreativeMD** [comment]
Most PlayerRevive has problems with are (depending on what version you are using):
* PotionsCore
* FirstAid
* Spice Of Life: Sweet Potato Edition

**Comment by CreativeMD** [comment]
I will close this issue for now. If the issue still persists post your mod list here.
