### ISSUE TITLE
feature request: configurable option to needing a certain item to revive a player

### ISSUE THREAD

**Issue by ZeliotL** [CreativeMD/PlayerRevive#129]
could you add the option where you would need a certain item in your inventory/holding to be able to revive someone?

for example, maybe you would need a totem of undying to revive the downed player, or maybe you want it to be an golden apple instead.
note: would also be nice if it worked with modded items

**Comment by CreativeMD** [comment]
This is actually possible. Use the command /cmdconfig, there you can go through all the settings. There is a setting for a revive item.
