### ISSUE TITLE
Self revive bug

### ISSUE THREAD

**Issue by SFort** [CreativeMD/PlayerRevive#13]
If a player gets kicked while they are down they will be revived when they reconnect.
PlayerRevive v1.2.11

**Comment by CreativeMD** [comment]
Are there any other mods installed?

**Comment by SFort** [comment]
I can't find the modpack build that caused this, so I'm going to assume that whatever mod was causing it, has fixed it in a update.(Sorry for bothering you)

**Comment by CreativeMD** [comment]
That's good to hear :D
