### ISSUE TITLE
exiting the game while downed puts the player back at the original spot

### ISSUE THREAD

**Issue by ilvro** [CreativeMD/PlayerRevive#132]
if you leave the game while youre downed, you respawn at the same spot where you were at. this essentially cheats death since you just get all of your items back for free with no consequences

**Comment by CreativeMD** [comment]
Normally the player will die when exiting the game while being downed. What version of minecraft are you using? There are issues with magma and mohist. I need more information to tell what is causing it.

**Comment by CreativeMD** [comment]
Still there?

**Comment by ilvro** [comment]
my bad, i forgot about this
looks like its an issue on my end, im running a server with 100+ mods and it doesnt happen on worlds without the other mods. most likely some mod that handles character loading or respawning and interferes with playerrevive
sorry!

**Comment by CreativeMD** [comment]
FirstAid is a known mod which can cause this issue.
