### ISSUE TITLE
Consume Revive item not working

### ISSUE THREAD

**Issue by ZeroAresIV** [CreativeMD/PlayerRevive#133]
While trying to revive someone with "Require revive item" and "Consume Revive Item" enabled, the item is not consumed after reviving the player. (Mc 1.18.2, also using First Aid mod)

**Comment by CreativeMD** [comment]
Fixed this issue in the version for 1.20.1. Unfortunately I do not support 1.18.2 anymore. You will have to update to receive the fix. Thanks for reporting this issue!
