### ISSUE TITLE
F5 Glitching

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/PlayerRevive#135]
Versions:
Minecraft: 1.20.1 
Neoforge: 47.1.84
Creative Core: 2.11.18
Player Revive: 2.0.21

When you die and go into f5, you start glitching on the ground.
![2024-01-06_02 39 58](https://github.com/CreativeMD/PlayerRevive/assets/8508976/666601fe-ad79-4655-8b89-a1d5e448f0da)
![2024-01-06_02 39 58_2](https://github.com/CreativeMD/PlayerRevive/assets/8508976/33ca5ff9-5a19-481b-bd21-85188b0fa316)
Basically just going between these two really quickly and bugging out :/

**Comment by CreativeMD** [comment]
Fixed in the newest version. Make sure to update CreativeCore as well.
