### ISSUE TITLE
Hide Particles of effect

### ISSUE THREAD

**Issue by AntonyCilleros** [CreativeMD/PlayerRevive#136]
hiding the particles of Slowness 3 when down would be great.

Also, Idk if it's already possible but I would like to add a weakness effect when revived and hide the particles.
Like the command "/effect give player minecraft:weakness 60 0 true"

actually here are the effects I wrote in the config file but their particules are visible : 
    "revivedEffects": [
      {
        "effect": "minecraft:blindness",
        "amplifier": 4,
        "duration": 200
      },
      {
        "effect": "minecraft:slowness",
        "amplifier": 0,
        "duration": 2400
      },
      {
        "effect": "minecraft:weakness",
        "amplifier": 0,
        "duration": 6000
      }
    ],

**Comment by CreativeMD** [comment]
You should use the command /cmdconfig and change the stuff there. Update CreativeCore and PlayerRevive an option has been added. Thanks for your suggestion!
