### ISSUE TITLE
1.20.1 error

### ISSUE THREAD

**Issue by alexkarpe** [CreativeMD/PlayerRevive#137]
My game doesn't open on forge 1.20.1 I have fully updated revive and creativecore
I use rubidium please help
[latest.log](https://github.com/CreativeMD/PlayerRevive/files/13955585/latest.log)
![Screenshot (179)](https://github.com/CreativeMD/PlayerRevive/assets/156851217/a243b8cf-e28c-4296-a629-66f69ca1a03a)

**Comment by AlexY-ml** [comment]
downgrade your playerevive version by one, 2.0.20.2 crashes, while PlayerRevive_FORGE_v2.0.21_mc1.20.1 works fine.

**Comment by alexkarpe** [comment]
Thank you so much it works perfeclty!

**Comment by CreativeMD** [comment]
You need to update CreativeCore and PlayerRevive.
