### ISSUE TITLE
Crash with latest update 2.0.22

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/PlayerRevive#138]
player revive: 2.0.22
creative core: 2.11.19 
https://gist.github.com/mxnmnm/01add7fe79bd4ecebd92be4748c2e957

**Comment by baegol** [comment]
Sorry if this type of input isn't wanted here, but I can confirm that this person is not the only one. I got the same mod loading error after updating to the latest versions.

**Comment by CreativeMD** [comment]
Update CreativeCore.

**Comment by mxnmnm** [comment]
curseforge being dumb and not approving it smh

**Comment by CreativeMD** [comment]
it got lost during the upload somehow. It is available now. Otherwise it's also available on modrinth.
