### ISSUE TITLE
Compatible with corpse

### ISSUE THREAD

**Issue by Xikaro** [CreativeMD/PlayerRevive#139]
**Bug description**
When using the playerrevive mode, if you are kicked from the server or the game, or you simply quit before the countdown, the corpse will not spawn and will not be saved in the death history

**Steps to reproduce the issue**
1)Die
2) Log out of the server during the countdown
3) Go back
4) There is no corpse

**Expected behavior**
I wish the corpse was created

**Versions**
- Minecraft version 1.20.1
- Mod loader Forge 
- Mod loader version  47.2.6
- Mod version 2.0.22

**Other mods**
[corpse](https://www.curseforge.com/minecraft/mc-mods/corpse)

**Comment by CreativeMD** [comment]
You should report this issue to the Corpse Mod. PlayerRevive kills the player on disconnect. No idea why Corpse cannot handle it. I tested to check if the events are called and yes they are. So it must be something in their end.
https://github.com/CreativeMD/PlayerRevive/blob/1.20/src/main/java/team/creative/playerrevive/server/ReviveEventServer.java#L75
