### ISSUE TITLE
Player Revive seems to be nuking Baubles

### ISSUE THREAD

**Issue by Darkmega18** [CreativeMD/PlayerRevive#14]
A friend of mine has had her baubles be wiped after I revived her a few times. each time we've cheated them back in but it's exceedingly annoying cause we thought we were past the bauble eating when I installed tombmanygraves 2.

One time she revived and had them, but next time she died cause no-one else was on and the bauble wasn't returned from the tombmanygraves 2 mod which means it must've been destroyed beforehand during the player revive process.

My only other perpetrator is possibly Sync, which I'm on my way to test on the server now. :V

**Comment by Darkmega18** [comment]
ok, it seems to be you as far as baubles are concerned... 

cases tested:

- on revival, without sync clones active, baubles are destroyed player keeps inventory, no grave obviously.
- on death without sync clones baubles should get saved by tombmanygraves 2 after the fact. but baubles are already destroyed by the reviving process it seems. as tombmanygraves doesn't restore them as it is much touted to do so.
- On death with clones but revived by player revive, clones don't sync, player revives, baubles are dead.
- On Death with player revive but clones available. Player seems to die normally possibly due to the activation of proper death from a lack of reviving from this mod. However it is interrupted and player resyncs to a clone, but leaves behind a grave. Player still keeps equipment since sync seems to work differently in these later MC versions, but a set of the equipment is now in the grave where it can be picked up resulting in a dupe... :V 
-On death in singleplayer where player revive does not occur, grave drops, stuff is in grave it seems fine.
-On death in singleplayer with sync player resyncs to clone body with equipment the clone has but still spawns a grave with no stuff. some baubles become phantom baubles and continue to work until something replaces them. (hooked ender grapple and diamond grapples) but thats more a sync issue than yours. :V 

This was done through the mods in my modpack Transcendence here: 
https://minecraft.curseforge.com/projects/transcendence

inventory pets grave pet is present in the pack but wasn't used in the inventory at any point however a compatibility patch for tombmanygraves is in which supresses grave spawn and keeps inventory as per what the pet should do.

**Comment by AshleyWard** [comment]
We are also having baubles be wiped when downed. We do not have Sync, tombmanygraves, or inventory pets.

**Comment by CreativeMD** [comment]
I tried to reproduce this issue with Thaumcraft, Baubles, CreativeCore and PlayerRevive installed. Everything worked as it should. The items stayed in the inventory if I got revived and were dropped to the ground when I died. I'm not sure if the grave mod is the problem, but according to @AshleyWard this cannot be the problem, can you send me your mod list?

**Comment by AshleyWard** [comment]
https://minecraft.curseforge.com/projects/alvern-village/relations/dependencies

Mod list above - if it's working fine with those few mods it does sound like a mod conflict, but just not one of the ones that was guessed.

I tested taking player revives out, and baubles stop being lost on death. 
It seems to be happening when players are downed with playerrevives installed; items are lost if they get revived. I hadn't had a chance to test if things are lost if they time out/give up and actually die.

**Comment by CreativeMD** [comment]
It would be really helpful if you could try to find the mod causing the problem. Just try to reproduce this issue with only PlayerReive (including CreativeCore) and Baubles (and a mod adding a few items you can use) installed, if it works add more mods until it doesn't work anymore. That would save me a lot of time.

**Comment by Darkmega18** [comment]
issue with that is having to reload the server with mod reductions everytime and having someone to test with at the time. :V since in singleplayer the revive obviously doesn't proc. >_<'

I'm THINKING it's probably Sync in my case cause it also has a death prevention effect that fires and is kinda meant to make your player shatter into bits and then come back as one of your clones later... Since tombmanygraves isn't having the baubles brought into them after a death in my pack so it's happening before it gets to the actual full death part... so gonna do some science with all the bits that can potentially have gravity over death and see what happens. :V

**Comment by Darkmega18** [comment]
Alright. So. Findings. heres the minipack. we added aether legacy and jei afterwards also to test with it's accessories menu and for easier access to items.
[Death science and you-0.0.D.zip](https://github.com/CreativeMD/PlayerRevive/files/2273160/Death.science.and.you-0.0.D.zip)

Every situation I tried relating to death. on revive or death baubles were annihilated. 

although in the case of using charm of keeping, dieing with that, then reviving annihilated the entire inventory. 

But in the case of grave pet, he kept our inventories across a sync death which was cool, but baubles was still annihilated due to the player revive screen.

taking out player revive, allowed baubles to be kept in most if not all situations of switching, grave pet, charm of keeping and normal death and pick up. except for resync death due to graves but they interestingly came back on a relog as they were cached or something, I don't even know.

when keeping sync and turning on playerrevive again we had the same issues as prior. :V HOWEVER, we have just determined that upon a relog the baubles just magically pop out and end up on the ground after a revive.

this... then resulted in a breakthrough!

We found that the issue from our side was with twilight forest. I believe twilight forest is keeping some kind of cache for what baubles the player has so to use with their charms of keeping. A tier 3 charm would actually cause player revive to annihilate the entire inventory but we found upon leaving the game the items saved for the charm which never got to be used but still was consumed (hence annihilating the inventory seemingly) would just pop out of you as you leave the server letting you pick them up again when you rejoin. 

this is the line that always comes up:
09.08 04:07:15 [Server] Server thread/WARN [twilightforest]: Mod was keeping inventory items in reserve for player %s but they logged out! Items are being dropped.

this was the same deal with the baubles that we noticed earlier by accident with certain interactions. So relogging after a rez would pop them out and you'd pick them up and be fine, but after a death I'm not entirely sure about it. since the grave would show up and the baubles would once again be glitched into uncertainty since twilight forest goes and caches them and the cache is removed or something when you leave, but they were meant to go into the grave and be able to be picked up and stuff.

So I have reason to believe the issue is with an interaction between your revivaling and twilight forests caching and preparations to have charms of keeping working.

**Comment by CreativeMD** [comment]
Thanks a lot!!! I tested it myself and can confirm it. I reported the issue to the other of twilightforest, I hope he can fix the issue.

**Comment by Darkmega18** [comment]
GG well played. Heres hoping for a hasty reply and fix. :D

**Comment by CreativeMD** [comment]
They fixed it already in a newer version. You can find the download link in the referred issue. Thanks for reporting this issue. Hope you can enjoy the mod now without having to worry about these kind of glitches.

**Comment by Darkmega18** [comment]
dang. that was quick. but I don't see an update in curse. I need it on curse to update my modpack with. :V unless it updated in the time between me checking this last and having a shower... and hey, no problem, just doing my duty as a pack creator to report these kinds of things do to have more compatibility for everyone. :)
