### ISSUE TITLE
Server acts as if Revived player's is 1 block tall, like he is still in downed state

### ISSUE THREAD

**Issue by AikaBack** [CreativeMD/PlayerRevive#141]
After being revived, actions like shooting from bow or using buckets are done if the player is 1 block high like when he is downed still so you need to aim higher which is annoying and hard. Same happens when you stand in 1 block high water, you start losing air with only legs in water. 
Also revived players are sometimes seen from other players perspective running around as if they are still in downed state which looks funny but is bug nonetheless. 

Playing on 1.20.1-forge-47.2.20.

Mods versions:
CreativeCore_FORGE_v2.11.23_mc1.20.1
PlayerRevive_FORGE_v2.0.22_mc1.20.1

Full modlist: https://pastebin.com/zGKFTP54

**Comment by CreativeMD** [comment]
This issue should be fixed in the newest version of PlayerRevive. Thanks for reporting this issue!
