### ISSUE TITLE
[Forge] [1.20.1] The Aether mod grants players to bypass bleed out.

### ISSUE THREAD

**Issue by KateReller** [CreativeMD/PlayerRevive#142]
After going through all of my mods, it turns out that [The Aether](https://modrinth.com/mod/aether) mod lets players bypass bleed out by disconnecting when they are in the bleed out state.

**Comment by CreativeMD** [comment]
Is is a known issue with FirstAid and Spice Of Life (all versions except Onion). Can you send me your mod list?

**Comment by KateReller** [comment]
My (and my server's) modpack has been updated and has new mods. But [my logs](https://mclo.gs/a5fBbnk) from [my comment from a previous issue](https://github.com/CreativeMD/PlayerRevive/issues/116#issuecomment-1963410990) still shows the mods I had installed at the time this issue was created.

**Comment by CreativeMD** [comment]
I have reported the issue to the aether team. I tested it myself with just PlayerRevive and The Aether installed and the issue is still there. Let's hope the issue can be fixed.

**Comment by bconlon1** [comment]
You could likely solve this by setting the SubscribeEvent to a higher priority, if you want the kill behavior to be guaranteed. Let me know if that works. https://github.com/CreativeMD/PlayerRevive/blob/bec1bdf38aaf212908767a25d3822c7897290879/src/main/java/team/creative/playerrevive/server/ReviveEventServer.java#L71

**Comment by CreativeMD** [comment]
Actually that works! Thanks @bconlon1 for suggesting this solution (probably by far the easiest). New version with this fix is out.
