### ISSUE TITLE
[Forge] [1.20.1] Mod is incompatible with Iron's Spells 'n Spellbooks

### ISSUE THREAD

**Issue by rafaelkai** [CreativeMD/PlayerRevive#143]
During bleedout state you are still able to cast [Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/) spells, causing obvious balancing issues.

**Comment by CreativeMD** [comment]
Reported this issue to Iron Spell's because this is something I cannot fix from my end: https://github.com/iron431/irons-spells-n-spellbooks/issues/359

**Comment by GreenForzeGaming** [comment]
noticed this today aswell. any fix?

**Comment by CreativeMD** [comment]
Nope and it seems like there won't be one. I don't see a good way to fix it from my end. Unfortunately forge does not provide a good way to block all ingame interactions. Especially if mods do something out of the box.

**Comment by GreenForzeGaming** [comment]
what if the revival screen instead off moving around made gui. a gui cant be closed with other buttons and cancels out all other interactions. make a gui screen that has 2 buttons 1 greyed out that says revive that activates after a player has done the revival thing. and a button that activates after set seconds that sayes respan.

**Comment by CreativeMD** [comment]
I will close this issue for now. Unfortunately the author is not really willing to help out here.
