### ISSUE TITLE
[Forge][1.20.1]Players can use command and send message when they are bleeding...

### ISSUE THREAD

**Issue by Star-Jirachi** [CreativeMD/PlayerRevive#144]
Players can use command and send message when they are bleeding...
I hope that I can stop it.

**Comment by CreativeMD** [comment]
That's intended. Why should that be forbidden?

**Comment by Star-Jirachi** [comment]
> 这是有意的。为什么要禁止这样做？
Thanks for reply :)
In the server, bleeding players can teleport to other players.

**Comment by Star-Jirachi** [comment]
> > Thanks for reply :)
> > In the server, bleeding players can teleport to other players.

**Comment by Star-Jirachi** [comment]
> That's intended. Why should that be forbidden?

Thanks for reply :)
In the server, bleeding players can teleport to other players.

**Comment by CreativeMD** [comment]
Players can tp themselves out of danger anyway? Would I could do is set the permission to zero while being downed, but this will most likely not work correctly with command plugins.

**Comment by CreativeMD** [comment]
Actually that feature exists already. Use the command /cmdconfig -> playerrevive -> bleeding. Set changePermissionLevel to true and set permissionLevel to zero.
