### ISSUE TITLE
Twilight Forest Charm of Keeping issue

### ISSUE THREAD

**Issue by Silvertide7** [CreativeMD/PlayerRevive#145]
I have a strange bug and I'm not sure if it should be reported here or on Twilight Forest side. When I have a charm of keeping and I am downed sometimes it consumes the charm of keeping and removes certain items based on the charm that was consumed. These items disappear from my inventory after I am helped up. These are stored in the twilight forest PlayerData until I die again. When I die again I do respawn with those items, so at least it's not permanently lost.

I'm not sure if this is an issue with charm of keeping getting triggered unnecessarily or if this mod is triggering the DBNO state in a way that might trigger the charm of keeping. I'm not sure if that can be helped at all.

I was thinking it might also be because you both have `@SubscribeEvent(priority = EventPriority.HIGHEST)` for your `PlayerDeathEvent`. So sometimes it triggers the charm of keeping to do its thing first (remove the items from the players inventory and store them to put back on the respawned player) and other times yours triggers first and you cancel the event so it never goes through to the charm.

Not sure on a good solution unless there is an `EventPriority.HIGHEREST` or the Twilight Forest mod is okay with moving theirs down one priority as yours should take effect first always.

**Comment by CreativeMD** [comment]
Sorry for responding that late. Sounds like the easiest solution would be if they go down one priority. If that does not cause an issue with other mods it should work with PlayerRevive. Can you report it to them?

**Comment by Silvertide7** [comment]
No problem! Yeah I did report it to them and they're considering going down
a priority. They said the issue was the gravestone mods were using high so
they had to use highest, but it seems like most of them have moved down
from high so at some point that will be fixed.

**Comment by CreativeMD** [comment]
Are there any news? I do not see a way to fix it from my end anyway, so I will close this issue for now. If you need any help you can still reply here.
