### ISSUE TITLE
leaving game and relogging revives you on the death spot and also keeps your exp you should have lost

### ISSUE THREAD

**Issue by GreenForzeGaming** [CreativeMD/PlayerRevive#146]
literly title
1.20.1 latest version

**Comment by CreativeMD** [comment]
What mods do you have installed?

**Comment by GreenForzeGaming** [comment]
![image](https://github.com/CreativeMD/PlayerRevive/assets/62345403/cb50174f-2012-4f69-aa9e-45b406861938)
![image](https://github.com/CreativeMD/PlayerRevive/assets/62345403/5696deb7-6a65-44f1-b49d-daf39f0266d0)
![image](https://github.com/CreativeMD/PlayerRevive/assets/62345403/a5f47dd6-2c45-453c-8a88-0604ef95f6ea)
![image](https://github.com/CreativeMD/PlayerRevive/assets/62345403/b5acd5f9-73d3-46b8-947e-679404b0b57e)

**Comment by CreativeMD** [comment]
Released a new version, which might fix your issue. Can you test it (it's 2.0.25)?

**Comment by GreenForzeGaming** [comment]
just got it updated, will see if its fixed.

**Comment by CreativeMD** [comment]
Any news on that so far?

**Comment by CreativeMD** [comment]
Will close this issue for now.
