### ISSUE TITLE
[suggestion] Born in Chaos Death Totem Compatibility

### ISSUE THREAD

**Issue by Poke5555** [CreativeMD/PlayerRevive#148]
can you make it compatible with the death totem from [Born in Chaos](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos) at the moment it you go down and if your health becomes low enough while down it triggers the totem and you regen health but stay down, or is this something the Born in choas dev would have to fix?

**Comment by CreativeMD** [comment]
You should report the issue to them and post it here. I will join the conversation and maybe we can figure out a fix.

**Comment by Poke5555** [comment]
they seem uninterested in compatibility 
![image](https://github.com/CreativeMD/PlayerRevive/assets/21167484/b38bbaef-0d1a-4946-ab64-221e2d738c27)

**Comment by CreativeMD** [comment]
Sorry for responding quite late. I answered to the comment on curseforge maybe the author changes its mind? We shall see. I will close this issue for now!
