### ISSUE TITLE
[1.20.1] Serious framerate drops while downed for some systems

### ISSUE THREAD

**Issue by Cixon** [CreativeMD/PlayerRevive#149]
**Issue:** Framerate drops significantly while downed on [essential](https://www.curseforge.com/minecraft/mc-mods/essential-mod) multiplayer play.
**CPU:** AMD Ryzen 3 3250U with Radeon Graphics

**Source:** Possible source of issue is the blur effects that occur when downed. I'd recommend adding a option to config that disables blur effects from rendering on the client. No log necessary.

**Version History:**
PlayerRevive_v2.0.25_mc1.20.1
Neoforge 47.1.99

**Comment by Cixon** [comment]
![Screenshot_2024-04-24_023223](https://github.com/CreativeMD/PlayerRevive/assets/69068153/e25b2f0a-31dd-442c-a53c-8e4baebfa739)

![Screenshot_2024-04-24_023205](https://github.com/CreativeMD/PlayerRevive/assets/69068153/d5ca056a-78d5-4e85-9a7f-ff9f55b94f86)

**Comment by CreativeMD** [comment]
Can you try to disable the shader effect to see if it fixes it? Use the command /cmdconfig ->playerrevive -> bleeding -> hasShaderEffect set it to false.

It is not a client option because it would be unfair if you could disable this negative effect.

**Comment by Cixon** [comment]
![Screenshot_2024-04-26_233936](https://github.com/CreativeMD/PlayerRevive/assets/69068153/1523a31c-f9a8-44bb-85e7-021a119a5575)

![Screenshot_2024-04-26_233948](https://github.com/CreativeMD/PlayerRevive/assets/69068153/1d2c8ee5-4909-4b38-aa24-a5054f042567)


this seemed to have fixed the issue. thanks!

> It is not a client option because it would be unfair if you could disable this negative effect.

understandable but, can we please have it as a option in the base-kit client config so that way mod-pack creators will have the ability to remove it for these circumstances? if anything, the modpack creator can add blindness in addition to the already existing slowness to make it more fair without hurting performance.

**Comment by CreativeMD** [comment]
You can just use the /cmdconfig command in singleplayer. It makes no difference for a modpack creator. Client side setting only means each client can decide on this setting for themselves. The other settings are forced by the server, like the shader thing. So just set hasShaderEffect to false add blindness and export the config files.
