### ISSUE TITLE
Issue/Feature Suggestion: Inventory screen being accessible in bleeding state

### ISSUE THREAD

**Issue by CodySpirits1** [CreativeMD/PlayerRevive#150]
Downed players are currently able to access their inventory while in a bleeding state, which can mess with the balance of other mods that also use death in some way, such as Iron's RPG tweaks (it damages gear on the hotbar and in armor slot upon actual death)
The possible fixes mentioned in the comments of Player Revive are as follows:

1. An option to prevent any screen to be displayed while bleeding (but this could cause new issues.) 
2. An option to prevent specifically the vanilla inventory from being opened (though this would not address modded inventory screens from being able to mess with things)
3. The tools could be damaged as soon as the player enters the bleeding state

**Comment by CreativeMD** [comment]
Open on issue there (links is above).

**Comment by CreativeMD** [comment]
Hey sorry for responding quite late here. At the moment I do not have the time to work on this issue. If rpg tweaks updates to 1.21 and you still need this fix let me know then I will try to get it done.
