### ISSUE TITLE
Issue: Totem of undying not functioning in curio slot

### ISSUE THREAD

**Issue by CodySpirits1** [CreativeMD/PlayerRevive#151]
Mods that allow the Totem of Undying into the curio slot as well as mods that would allow it to work in the player's inventory don't seem to function with PlayerRevive, and only seem to function when held in the off hand or main hand, just as in vanilla.

**Comment by CreativeMD** [comment]
Do you know which mods can do that? Because we need to report the issue to them.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If the issue still persists reply here with the requested information.
