### ISSUE TITLE
[1.19.2] How to change the time of death when left-clicking

### ISSUE THREAD

**Issue by bmd070** [CreativeMD/PlayerRevive#154]
I am using the latest version of this mod, and I have not found a configuration setting for this, I do not know where to change this time. Thanks in advance for the answer!

**Comment by CreativeMD** [comment]
This config option is available using the command /cmdclientconfig -> playerrevive -> bleeding -> giveUpSeconds. Not sure if this is available in 1.19.2 though. This version is quite outdated.
