### ISSUE TITLE
[NeoForge 1.20.4.235] No one in the server can die. It just appear a message saying "{Username} is bleeding. {Username} died from __"

### ISSUE THREAD

**Issue by AikamiT** [CreativeMD/PlayerRevive#155]
Good afternoon,

At first, I thought that the fact that we can't die was happening because another mod was incompatible with Player Revive, but I made a test server with only this mod and it worked the same way.

I don't know, do I have to change a config file, is it broken or is it a problem with the NeoForge version?

I'll put an image to show what I'm talking about (never appeared the message or song to be revived)
![PlayerRevive not working](https://github.com/CreativeMD/PlayerRevive/assets/74986182/aee16711-8e24-4d25-8e5a-16c844845fe2)

Greetings!

**Comment by CreativeMD** [comment]
Please update to Minecraft 1.20.6. Then things should work again.
