### ISSUE TITLE
Problem with mod Raised

### ISSUE THREAD

**Issue by LumenzAeternum** [CreativeMD/PlayerRevive#158]
![изображение](https://github.com/CreativeMD/PlayerRevive/assets/109238105/24e46315-7f0d-4172-8c59-d78424955e19)
1.20.1 neoforge

**Comment by CreativeMD** [comment]
You should report it to the author of the mod raised. Something is messed up in the renderer. Furthermore I do not really support 1.20.1 neoforge. I currently support 1.20.1 Forge and 1.21 NeoForge. So that might be an issue as well.
