### ISSUE TITLE
Mod failing to load on server

### ISSUE THREAD

**Issue by darthyison** [CreativeMD/PlayerRevive#159]
Hi! I started using player revive mod on a free aternos server (neo forge 1.21) and worked fine for a few days and then server couldn't load the mod. And I don't know why.

I share log. Aternos couldn't help :/ 
https://mclo.gs/j7lQxuD

**Comment by CreativeMD** [comment]
Actually your NeoForge version was too new. I have updated PlayerRevive to be compatible with the newest NeoForge version. Simply update and your issue should be fixed.
