### ISSUE TITLE
Extreme lag roll when turned to stone by medusa in ice and fire and knocked out player not TPable

### ISSUE THREAD

**Issue by Darkmega18** [CreativeMD/PlayerRevive#16]
Hey @CreativeMD , was at it again and this time my friend blundered into a Gorgon ruin for a look probably not knowing how deadly they are, Apparently she went in for a look around only to get turned to stone which resulted in a really massive lag roll of doom. 

Because the medusa is meant to turn you to stone as an instagib if you look right at it probably caused some shonky looping business for a bit until it caught up cause friend wasn't being outright killed but just got knocked down. I TP'd her to me but the body wouldn't show up so we had to relog which resulted in death, and somehow, pants/chestplate destruction for no apparent reason. :V 

Then to add insult to injury during said reconnect it took the server with it so it restarted. Still left a statue though it seems.
https://cdn.discordapp.com/attachments/263952787770048513/478472541535469578/unknown.png

The crash it spat was related to minestuck's Captchalogue and a revive event however. which is here:

[crash-2018-08-13_03.38.43-server.txt](https://github.com/CreativeMD/PlayerRevive/files/2282838/crash-2018-08-13_03.38.43-server.txt)

**Comment by CreativeMD** [comment]
What's the name of the mod? I need to the damagesource so I can exclude it.

**Comment by Darkmega18** [comment]
Ice and Fire, Dragons in a new light.

**Comment by CreativeMD** [comment]
I hope this version fixes it: https://www.dropbox.com/s/civdpmohzxvwuby/PlayerRevive_v1.2.17_mc1.12.2.jar?dl=1
Can you test it?

**Comment by CreativeMD** [comment]
Does this version fixes it? https://www.dropbox.com/s/civdpmohzxvwuby/PlayerRevive_v1.2.17_mc1.12.2.jar?dl=1

**Comment by Darkmega18** [comment]
you sent that already. but I haven't had time to check it yet. sorry, shoulda said something. I can get player revive active just by being in LAN right? so I can just check it sorta matter-of-factly using singleplayer? I'l get to it tomorrow if thats the case.

**Comment by CreativeMD** [comment]
Yes you can do so. Sorry I couldn't see my first message, so I wrote another one.

**Comment by Darkmega18** [comment]
Good news. it works, and I'm now a statue and the game hasn't had a mental breakdown trying to wonder while I still exist.... However, ice and fire gotta fix turning to stone for everything else. cause literally everything thats not from their mod that gets turned to stone still keeps on doing it's thing, albeit with it's animations somewhat frozen. >_>

**Comment by CreativeMD** [comment]
Ok, but his is not an issue of PlayerRevive, right? Correct me if I'm wrong.

**Comment by Darkmega18** [comment]
yeah, it's apparently a mowzie+ice and fire issue. not yours. but one bug squished.
