### ISSUE TITLE
Player Revive 1.18.2

### ISSUE THREAD

**Issue by ssergiio17** [CreativeMD/PlayerRevive#161]
I have a problem that i never had before, i used to play on aternos with the version 1.12.2 and i never had this problem, i actually have to problems, i copy paste them here.
<html>
<body>

PlayerRevive (playerrevive), Version: 2.0.14
--
33 | Issue tracker URL: https://github.com/CreativeMD/PlayerRevive/issues
34 | at TRANSFORMER/playerrevive@2.0.14/team.creative.playerrevive.PlayerRevive.<clinit>(PlayerRevive.java:44)
35 | Stacktrace:
36 | at team.creative.playerrevive.PlayerRevive.<clinit>(PlayerRevive.java:44) ~[PlayerRevive_FORGE_v2.0.14_mc1.18.2.jar%23102!/:2.0.14] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}

</body>
</html>

And the second problem is the one i put here:
<html>
<body>

Mod File: /server/mods/PlayerRevive_FORGE_v2.0.14_mc1.18.2.jar
--
40 | Failure message: PlayerRevive (playerrevive) has failed to load correctly
41 | java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'
42 | Mod Version: 2.0.14
43 | Mod Issue URL: https://github.com/CreativeMD/PlayerRevive/issues
44 | Exception message: java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(int, org.apache.logging.log4j.Logger, net.minecraft.resources.ResourceLocation)'

</body>
</html>

**Comment by CreativeMD** [comment]
Update CreativeCore and PlayerRevive, this should fix your issue.
