### ISSUE TITLE
Command don't work when reloading the server / world

### ISSUE THREAD

**Issue by 0xy49** [CreativeMD/PlayerRevive#162]
The command /revive don't work after reloading the server / World

Step to reproduce :
1. Load a world or a server
2. Kill yourself by a monster or /kill, the command appaer
3. Revive yourself with the command
4. Reload the world with /reload
5. Kill yourself
6. The command doesn't appaer

**Comment by CreativeMD** [comment]
What version of minecraft are you using?

**Comment by 0xy49** [comment]
1.20.1
forge 47.3.5

**Comment by CreativeMD** [comment]
Is fixed in the newest version. Thanks a lot for reporting this issue!
