### ISSUE TITLE
1.21 Fabric

### ISSUE THREAD

**Issue by WhyAreLess** [CreativeMD/PlayerRevive#163]
Are there any future plans to add Fabric support to PlayerRevive? 
Love the EnhancedVisuals mod btw, really like the immersion it gives!

**Comment by artonoesperson777** [comment]
me too i want fabric @imonxza

**Comment by CreativeMD** [comment]
At the moment there are no plans to do so. Don't have the time at the moment also I rely heavily on Forge Events. A version for fabric would require a rewrite of major parts of the mod, yet alone would cause difficulties on forge if I try to unify it. So I would have to basically maintain two different mods, which I'm not willing to at the moment.

**Comment by TatleCat** [comment]
pity, fabric 1.20.1 :(
