### ISSUE TITLE
Epic Fight incompatibility

### ISSUE THREAD

**Issue by Walrus98** [CreativeMD/PlayerRevive#165]
When you are down you can press the R key to enter combat mode and keep fighting until you die permanently

![image](https://github.com/user-attachments/assets/c359431b-466d-457f-a24a-410506de3626)

**Comment by CreativeMD** [comment]
This is a known issue: https://github.com/Yesssssman/epicfightmod/issues/1090
I cannot do anything from my end. Unfortunately the author has not responded yet.
