### ISSUE TITLE
Disconnecting from the server does not kill the player. Sometimes revives them on relog.

### ISSUE THREAD

**Issue by WaterClock-TM** [CreativeMD/PlayerRevive#167]
Heya,
Version: PlayerRevive_v2.0.0-pre04_mc1.16.5.jar
MC Version: 1.16.5

This is as part of the Decursio modpack.
I wondered if it was a strange interaction with the Corpse mod so removed that but didn't resolve the issue.

I didn't notice any of the mods that have been specifically called out in previous issues that can cause this problem, apologies if I missed anything!

Modlist:
![image](https://github.com/user-attachments/assets/2f4283ce-bbc9-404b-8e81-8ce971ea4a32)
![image](https://github.com/user-attachments/assets/1c424f49-688f-4dc2-9f87-345773d3c9d0)
![image](https://github.com/user-attachments/assets/896aee79-aecf-4195-a853-aa2bd793c322)
![image](https://github.com/user-attachments/assets/0aa2e68d-3163-439e-92ac-b1258540f5f6)
![image](https://github.com/user-attachments/assets/6a48fcb6-ed28-4d72-b27a-1052cc7493ff)

**Comment by WaterClock-TM** [comment]
Please do let me know if there is any other information I could provide that might be helpful :)

**Comment by CreativeMD** [comment]
FirstAid, PotionsCore and Mohist caused an issue like this. Sorry, but 1.16 has been long time gone and is not supported anymore. I can only recommend to upgrade.

**Comment by WaterClock-TM** [comment]
No worries, thanks for responding.
