### ISSUE TITLE
[Suggestion] Finisher, customizable post revive hearts/hunger and Boons

### ISSUE THREAD

**Issue by Darkmega18** [CreativeMD/PlayerRevive#17]
For the case of maybe Teambased PvP and such, a player just being knocked down can provide a certain level of gameplay impetus. In this case, Teammates would want to rush to get a friend up. However, the enemy team would want said friend on the enemy team to be ded.

So I'm thinking, rather than just being for revive. Someone can instead act to finish off another player resulting in over their white revive bar, a crimson red execution bar. Execution being done by shifting and ATTACKING the downed player. 1 attack each second allowed for a quarter of a bar. All of the bar filled results in an execution finish that makes the player rip in pieces.

On the other side, a maker should be able to set the amount of hearts and food a player is revived on when reviving, possibly while holding certain configured items improves it further allowing you to hold certain key items like healing items or trinkets which improve revive levels and get people back into the fight quicker.

Then for both sides there could be tools types or specific tools or items that provide the revived, reviver, or killer when used to revive or kill a player with customizable buffs through a json. Like say reviving using an item could provide them with a speed boost and light regeneration or could just revive them on a higher amount of food/health outright.
Likewise a killer could get certain items off a player by murdering them with specific items or just by default.

Then to top it off, if you've got someone executing but only get half executed before you get revived by someone interjecting a player can get revived on lesser health or hunger as a penalty.

yay? :D

**Comment by CreativeMD** [comment]
I like the execution part, but I'm not sure about the other stuff. The health and food level after being revived is configurable. I'm not sure if those items would make any sense, I would rather heal the player once he is revived. Maybe a mod which adds the ability to use certain items on your teammates (such as a med-kit for example), but I doubt it fit to PlayerRevive itself.
I like the idea of configurable buffs or potion effects you have after being revived, maybe effects like nausea, slowness or blindness. Would also be cool to have an additional potion effect quick revive, which allows you to revive somebody else faster.

What do you think about it?

**Comment by Darkmega18** [comment]
We can go with that.

Executions, potion effects on revive. Healing touch potion that makes you revive others faster. While a second wind potion to self revive and gain temporary immunity to let you get back on your feet then dispels the effect afterwards? :D

**Comment by CreativeMD** [comment]
Sorry, it's been far too long. I was pretty busy doing other stuff.
Self revive might be a bit overpowered.

I added the ideas to my todo list. I don't know when I will implement them, maybe when I port the mod 1.13 (don't know for sure). Thanks for all your suggestions and feel free to post more.
