### ISSUE TITLE
When you die and then you log out the server and enter again you revive yourself

### ISSUE THREAD

**Issue by Angelous-UI** [CreativeMD/PlayerRevive#172]
Am playing with my friends with the mod essential and a modpack, and when whoever of us die, they can log out the server and then enter again for revive themselves, and i dont know why is that.

[latest.log](https://github.com/user-attachments/files/17757283/latest.log)

this is my last log, if need something extra, say it

**Comment by Angelous-UI** [comment]
i forgot to say that am playing in 1.18.2 and with the 2.0.13 version of the mod

**Comment by CreativeMD** [comment]
That's probably caused by another mod. Maybe FirstAid or by the server platform you are using. I know there are issues with Mohist for example. I do not support 1.18.2 anymore. I can only recommend to update to a newer version.
