### ISSUE TITLE
[Forge 1.19.2] Incompatible with Ars Nouveau

### ISSUE THREAD

**Issue by TheROFL98** [CreativeMD/PlayerRevive#173]
When triggering the Thread of Undying by killing a player, the PlayerRevive mod takes priority first, and the Thread of Undying only gets triggered once the player is damaged past the downed state, making the Thread of Undying essentially useless.

Forge 43.4.4
Ars Nouveau 3.23.0
PlayerRevive 2.0.17

**Comment by CreativeMD** [comment]
Sorry, but I dropped support for 1.19.2 a long time ago.
