### ISSUE TITLE
Chat Problem and Permission

### ISSUE THREAD

**Issue by Meidde** [CreativeMD/PlayerRevive#175]
I've already seen you talking about using "PermissionLevel" to prevent players from using commands like /spawn. This may work on regular Minecraft servers, but not on servers that are governed by permission plugins like mine, which is via Luckperms, where permissions are all based on this plugin.

My suggestion is not just a suggestion, but an appeal. I really need a setting that allows me to disable chat for players who are down on the ground, so that it can somehow prevent them from trying to cheat death.

**Comment by CreativeMD** [comment]
Added a config option to prevent the opening of the inventory gui. Use the command /cmdconfig and enable the option `playerrevive` -> `bleeding` -> `disableChatAccess` or `playerrevive` -> `bleeding` -> `disableServerCommands` (to prevent commands only)
