### ISSUE TITLE
issue: players can open the inventory when in dying state.

### ISSUE THREAD

**Issue by Ryuuunosuke** [CreativeMD/PlayerRevive#176]
I'm creating a modpack, and use some other mods to punish players for dying, like leaving only their armor and curios in their corpses ( corpse mod x configurable death), so this would break this mechanic, as players would be able to transfer everything to an inventory like a backpack, before bleeding out completely.
would you be able to introduce this feature?

**Comment by CreativeMD** [comment]
Added a config option to prevent the opening of the inventory gui. Use the command /cmdconfig and enable the option `playerrevive` -> `bleeding` -> `disableInventoryAccess`.

**Comment by Ryuuunosuke** [comment]
i can still open other iventories like curios and sophisticated backpacks, could you stop it?

**Comment by CreativeMD** [comment]
Added another option in the newest version which should fix that issue as well.
