### ISSUE TITLE
Not dying after leaving server.

### ISSUE THREAD

**Issue by SlenKen** [CreativeMD/PlayerRevive#178]
If you are downed and rejoin server, you aren't down. It can be really badly abused, and literally never die.

**Comment by CreativeMD** [comment]
What mods are you using? What minecraft version? What server platform? Normally this does not happen. You will die if you leave.

**Comment by SlenKen** [comment]
I'm playing on 1.19.2. I've been using 2 different hosting platforms, it was ServerCraft before and now it's EnderChest, the same issue on both. After you leave there is a chat message about your death, but you spawn on your body like you've been rescued. I attached mod list in a file.
[mod list.txt](https://github.com/user-attachments/files/18034737/mod.list.txt)

**Comment by CreativeMD** [comment]
In 1.19.2 there are issues with FirstAid and Mohist. Unfortunately I do not support 1.19.2 anymore. I cannot help you there, sorry. They only way to fix it is to get rid of the incompatible mod/ server architecture.

**Comment by SlenKen** [comment]
Do you do commisions? If yes, how much would it be for fixing my issue?

**Comment by CreativeMD** [comment]
It's not easy to fix and I doubt it is worth. Rather consider updating.
