### ISSUE TITLE
Baubles disappearing on death

### ISSUE THREAD

**Issue by Minamikaze392** [CreativeMD/PlayerRevive#18]
I'm using PlayerRevive mod in my server along with Baubles-1.12-1.5.2(used by thaumcraft 6, botania etc.). In the current version of Baubles, when players die the baubles don't drop and remains equiped after respawning. However with PlayerRevive installed the players would respawn with no baubles equiped, neither having them dropped. They simply disappeared.

This issue does not happen in singleplayer, for obvious reason.

**Comment by CreativeMD** [comment]
Is Twilight Forest installed as well?

**Comment by Minamikaze392** [comment]
Ahh you're right~~~ I tried removing Twilight Forest and now the baubles are dropping out nicely on death.

**Comment by CreativeMD** [comment]
The issue has been reported before, you can find the fix for it here: https://github.com/TeamTwilight/twilightforest/issues/592
