### ISSUE TITLE
possible Crash with dissolution stopping the respawn screen coming up

### ISSUE THREAD

**Issue by Darkmega18** [CreativeMD/PlayerRevive#21]
So dissolution is a mod made by the ladysnake team. Basically makes it so you turn into a soul on death and can possess undead to get a body back and then do some things to get your body back to normal again. However I had both on the server and upon dieing and player revive ticking out the server unfortunately crashed because dissolution is meant to stop the respawn/titlescreen screen from coming up after a death but you probably make it come up in a different way or something. but heres the crash.

[crash-2018-10-05_02.23.16-server.txt](https://github.com/CreativeMD/PlayerRevive/files/2449158/crash-2018-10-05_02.23.16-server.txt)

**Comment by CreativeMD** [comment]
Can you test if this version fixes the issue? If not can you send me the log file?
https://www.dropbox.com/s/6klfulll5iltvt7/PlayerRevive_v1.2.20_mc1.12.2.jar?dl=1

**Comment by Darkmega18** [comment]
I'll give it a shot tomorrow then, since it's late and I just got done finding the source of another bug with another mod. But glad you figured something out with Pyro :D.

**Comment by CreativeMD** [comment]
Any news?

**Comment by Darkmega18** [comment]
oh, crap. I never got to it. D: I've been kinda minecrafted-out for a while. :<

**Comment by CreativeMD** [comment]
So will you try it out now, otherwise I will do it myself.

**Comment by Darkmega18** [comment]
ok! it works. setted it to LAN, then died with the skip respawn screen option set to false and it didn't crash once it hit the respawn screen and hitting respawn popped me out in the same spot I died like intended. and of course it works just fine if it's set to skip the respawn screen also by default.

**Comment by CreativeMD** [comment]
Nice! I will upload the fixed version to curseforge.
