### ISSUE TITLE
Amazing Bug

### ISSUE THREAD

**Issue by KenyMylankca** [CreativeMD/PlayerRevive#22]
Me and my friend were playing in my local world (LAN) and we died, both. He clicked give up then respawned, but i didn't. Because game crashed on i click "give up". After i relaunched the game, i was alive on the place, but mobs can't hit me. Then, i opened the world to local(lan) again, and then i died instantly on doing it. I clicked "give up" again, but it didn't work. So, i have wait the time that someone can revive me, so it finished, THEN the game crashed. And here's the crash report. Hope you can fix something with it.
[crash-2018-10-13_23.03.55-server.txt](https://github.com/CreativeMD/PlayerRevive/files/2475796/crash-2018-10-13_23.03.55-server.txt)

The crash report that happened first time i died with my friend, was about Backpacks mod by Brad, which is here: https://drive.google.com/open?id=1imrmWUdJW02zBDkRHrlnV5ZX1AaAvrpr

**Comment by CreativeMD** [comment]
Can you report this bug to the backpack mod? The second crash seems to be a follow crash. I don't know how to fix that one.

**Comment by KenyMylankca** [comment]
I already sent a message has link of this page to Brad.

**Comment by CreativeMD** [comment]
And what did he say about it?

**Comment by KenyMylankca** [comment]
![aaa](https://user-images.githubusercontent.com/41585837/47027846-e565da80-d170-11e8-81a4-8720f82c4701.PNG)

**Comment by CreativeMD** [comment]
So will it happen again or is it fixed now?

**Comment by KenyMylankca** [comment]
To be honest, i didn't try if it will crash again. If you want me do, i can do it.
If not, you can close this.
But losing my backpack and having the world corrupted was painful... :D

**Comment by CreativeMD** [comment]
Make a backup! But I was talking about does the second still occur or can you open the world to lan now?

**Comment by KenyMylankca** [comment]
ah no i tried it few times (4-5) it crashed at all with the same crash. so i had to delete the world.

**Comment by CreativeMD** [comment]
Can you create a new world, make it crash and then send it to me, so I can try to fix it?

**Comment by CreativeMD** [comment]
Are you still there?

**Comment by KenyMylankca** [comment]
Ah, sorry for forgot this bug. I tried this with my friend a few times while playing, and couldn't reproduce it again. You can close it if you wish. Thanks so much for helping tho

**Comment by CreativeMD** [comment]
Ok good to hear that, just reopen this issue if it happens again. Have a great time!
