### ISSUE TITLE
Timer+Reviving not working in v1.2.20

### ISSUE THREAD

**Issue by ThedafraDE** [CreativeMD/PlayerRevive#23]
In v1.2.20 Reviving a Player does not work.
While being dead , the Timer does not decrease and interacting with the Player
opens up the interface as you would expect it but there is no progress in the "Revive Bar",
which leaves giving up and disconnecting as the only option.

This was discovered on Forge version 1.12.2 - 14.23.5.2768 with the following mods.

https://www.dropbox.com/s/xre5rlree2ipkt0/mods.zip?dl=0

**Comment by CreativeMD** [comment]
Fixed it in v1.2.21 which should be available soon. Thanks for reporting this issue!
