### ISSUE TITLE
Crash after getting killed

### ISSUE THREAD

**Issue by Secretname2009** [CreativeMD/PlayerRevive#24]
I was running a LAN Server with my friend and while we was playing i died, but instead of sending me to the revive screen, me and my friend crashed along with the server.

The crash log mentions your mod and the normal log mentions your mod and the Baubles mod.
My guess is the Baubles mod and your mod doesnt like eachother, removing Baubles certainly fixed the crash so thats my best Guess. EDIT: It didnt, still crashed but didnt have the Baubles in the list for sure.

[crash-2018-11-12_22.12.07-client.txt](https://github.com/CreativeMD/PlayerRevive/files/2573661/crash-2018-11-12_22.12.07-client.txt)

[Informative Line.txt](https://github.com/CreativeMD/PlayerRevive/files/2573678/Informative.Line.txt)

**Comment by CreativeMD** [comment]
Oh sorry, that is my mistake. I uploaded a fix for it which should be available soon. Thanks for reporting this issue!
