### ISSUE TITLE
disconnect revive

### ISSUE THREAD

**Issue by saraminecraft** [CreativeMD/PlayerRevive#29]
Hi! Amazing mod!!! When players die on my server if they choose disconnect they come back to the game with half a heart but alive with all their stuff. Is this working as intended? I have players disconnecting and reconnecting over and over till they are able to get out of the death.

**Comment by CreativeMD** [comment]
So it does not happen every time? Is PotionsCore installed as well? In theory the player should die if he/she disconnects. If the player logs in again, the death screen should be displayed. Is that the case?

**Comment by saraminecraft** [comment]
Yes this happens every time, if you disconnect when you reconnect you have a heart and all your stuff. Yes PotionCore is installed is that a conflict? I truly apologize if so.

**Comment by CreativeMD** [comment]
Yeah, sorry. Either remove PlayerRevive or PotionsCore. The author has not replied yet to my issue: https://minecraft.curseforge.com/projects/potion-core/issues/2

There is nothing I can do about it. The only thing you can do is to disable the disconnect button. Players can still hit ALT + F4, but it will make it a little bit harder. Just download the newest version (I recommend to install IGCM) and set disableDisconnect to true.
