### ISSUE TITLE
game crash on loading

### ISSUE THREAD

**Issue by ilvrak** [CreativeMD/PlayerRevive#3]
MC 1.12.2
forge 2536
CreativeCore v1.9.4 mc1.12.2.jar
PlayerRevive v1.2.6 mc1.12.2.jar

**Comment by N247S** [comment]
It might be usefull to add a crashlog. without it its impossible to find the problem.

**Comment by CreativeMD** [comment]
Will be fixed in the next update, which should be available soon. Thanks for reporting this issue, but a crash log would have made it easier for me.
