### ISSUE TITLE
Request - Announce Coordinates 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CreativeMD/PlayerRevive#33]
So with Journey Map there is a chat current location hotkey but unfortunately it does not seem to work when downed. Making getting revived kind of hard when split up. Maybe even a beacon would be nice that lasts until you die.

**Comment by CreativeMD** [comment]
There is an option to do so already, but not sure if it's high enough.

**Comment by P3rf3ctXZer0** [comment]
It would be nice to actually shout the cords though.

**Comment by CreativeMD** [comment]
I will add an option to display the coordinates. Will also be part of the upcoming update. Let's hope i will find some time soon.

**Comment by P3rf3ctXZer0** [comment]
Thank you  :D
