### ISSUE TITLE
Request - Announce What Downed You

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CreativeMD/PlayerRevive#34]
So sometimes when asking for help people fall pray to what killed you. Maybe a tag like this would be cool.

MOB - Any living entities with mob style tag.
TRAP - Any block or such thing.
PK - A another user killed you.
UNK - Anything that did not get registered correctly.

**Comment by P3rf3ctXZer0** [comment]
It would read

USERNAME is bleeding... - Possible reason - PK

**Comment by CreativeMD** [comment]
Added your suggestion to my todo list. I don't know when I will find time to work on PlayerRevive. There are many requests and I will do them all once I have the time.

**Comment by P3rf3ctXZer0** [comment]
Thank you <3
