### ISSUE TITLE
Request - Random chance of player being revivable

### ISSUE THREAD

**Issue by ghost** [CreativeMD/PlayerRevive#35]
Basically, a config settings which lets server owners configure the chance of a player actually going into the revivable state, or just dying.
Also, maybe make it so that (configurable also) a headshot kills a player in FirstAid (I'm not sure if this is implemented or not)

**Comment by CreativeMD** [comment]
Not sure if that's a good concept. It does not make any sense to me, sorry :( Would be very frustrating if you have bad luck.
