### ISSUE TITLE
The disconnect button

### ISSUE THREAD

**Issue by Xitryne** [CreativeMD/PlayerRevive#36]
When one dies and one disconnects by the button of the mod "PlayerRevive" and that one reconnects one reappears on the tomb with a half, it is very problematic. I tried to disable the button by the config file but it does not work it still remains activate! The mods I have with are listed below. (Sorry I had to write with Google translation)
![Capture](https://user-images.githubusercontent.com/53669476/62422155-31592000-b6ae-11e9-9b94-4c92ff0396ab.PNG)
![Caepture](https://user-images.githubusercontent.com/53669476/62422157-34eca700-b6ae-11e9-926f-92cfe72b2055.PNG)

**Comment by Xitryne** [comment]
we appear on the tomb of the mod "Gravestone" with a half heart*

**Comment by CreativeMD** [comment]
There are some issue with PotionsCore (but it's not installed). You can remove the disconnect button, but people will still be able to close the game and reconnect.

Can you try it with only the grave mod installed (and PlayerRevive of course) and see if it still happens?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists make sure to reopen it (and try the described things above).
