### ISSUE TITLE
Getting kicked around like a soccerball while "knocked out"

### ISSUE THREAD

**Issue by Darkmega18** [CreativeMD/PlayerRevive#37]
In my modpack minestuck++, and also a different small pack i made for myself for testing in these later versions of forge with mods I've come across something rather silly and it is still apparently occuring my in minestuck++ modpack on twitch.

When you die to a bunch of mobs the mobs don't stop attacking you even if you're downed and you end up just getting kicked around like a soccerball or hackey sack while trying to get revived and it's just maybe a little dizzying and silly.  I'm unsure if maybe the invulnerability while knocked out isn't being set or something, but it could need a quick look at.

**Comment by CreativeMD** [comment]
Can you test if this version fixes the issue?
https://www.dropbox.com/s/wzjct85racldgq0/PlayerRevive_v1.2.27_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
Are you still there?

**Comment by Darkmega18** [comment]
I guess I died. Cause warframe and other shifts. :V

**Comment by CreativeMD** [comment]
I will close this issue for now. This will be different in the rewrite.

**Comment by Darkmega18** [comment]
alrighty. but I've recently come back and had some packs and I think the issue is kinda intermittent depending on what AI mods and such were involved in the pack.
