### ISSUE TITLE
Crash, in dead when send message.

### ISSUE THREAD

**Issue by Alee-OneHit** [CreativeMD/PlayerRevive#43]
Hello, you know that there is a problem that when you die, you try to write to your colleagues to revive you, and the crash, I sent you the page of the accident, does it have to do with the creativecore mod, does it have any solution?

https://paste.dimdev.org/iqizeyebun.mccrash

**Comment by CreativeMD** [comment]
Fixed, make sure to update CreativeCore and PlayerRevive.
