### ISSUE TITLE
Problem using a command when dead

### ISSUE THREAD

**Issue by Alee-OneHit** [CreativeMD/PlayerRevive#44]
hello you know that before the last 2 updates, I could run the command /revive, when it happened that you could not write in the chat when you were dead and cracked before that if you could use the command, now it can not and is admin for me is necessary, since I try things, would you open some way to implement it in the configuration to be able to enable and disable it? It is very useful especially when users die and need help from their colleagues to revive themselves using the /tpaccept (to the essentialsX). command, Is it possible that it can be implemented or fixed in a future update?...

**Comment by CreativeMD** [comment]
You can enable it in the configs, but not only overall and not for specific players. This might come in a future but not soon sorry.
