### ISSUE TITLE
Sound problem when dying

### ISSUE THREAD

**Issue by HeberonYT** [CreativeMD/PlayerRevive#45]
Hello, when I updated the PlayerRevive mod, the sounds stopped working when I died, also this message appears when loading my world, 
![Screenshot_2](https://user-images.githubusercontent.com/13698597/79290671-63a05b80-7e92-11ea-844d-302e3640f260.png)
![Screenshot_8](https://user-images.githubusercontent.com/13698597/79291383-2341dd00-7e94-11ea-964c-b4b2079e2a26.png)

I ignored it, but when I died I discovered what it meant, and now the music does not play when I surrender.
To fix it I have gone back to the old version.

**Versión OK:**
CreativeCore_v1.9.90_mc1.12.2.jar
PlayerRevive_v1.2.28_mc1.12.2.jar

**Version FAIL:**
CreativeCore_v1.10.10_mc1.12.2.jar
PlayerRevive_v1.2.32_mc1.12.2.jar

**Comment by CreativeMD** [comment]
I could not reproduce your issue. Maybe your download file is corrupted somehow? Maybe download it again?

**Comment by HeberonYT** [comment]
Thanks for the prompt response. I have downloaded the files again, but I keep getting the same error. Sounds do not appear to register correctly when starting the game, so they are removed from the world today.
![Screenshot_8](https://user-images.githubusercontent.com/13698597/79376758-4023f200-7f20-11ea-8c5e-25341db88802.png)

**Comment by HeberonYT** [comment]
The error only occurs on servers, not on singleplayer

To replicate the problem, do the following:
make a server and client with the following mods:
-forge-1.12.2-14.23.5.2847-universal
-CreativeCore_v1.9.90_mc1.12.2
-PlayerRevive_v1.2.30_mc1.12.2
Spawn in the world, die and press surrender, here the sounds will work fine.

Now update the mods:
-CreativeCore_v1.10.10_mc1.12.2
-PlayerRevive_v1.2.32_mc1.12.2
When you start the server you will receive the message of missing sounds, if it is omitted and enters the world, when you die the sounds will no longer sound when you surrender.

**Comment by CreativeMD** [comment]
Fixed it! Thank you very much for your help! Seems like the sound events were not registered on dedicated servers. The new version should be available soon. Hope everything works fine now.
