### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by HeberonYT** [CreativeMD/PlayerRevive#46]
Hello, I can confirm that the sound error is fixed, but there is another detail with the messages in the chat.
Although the server and client are sending messages in Spanish (so I have it configured) when someone dies, the message "<player> is bleeding ..." always appears in English.
The rest of messages, for example, disconnect from the server, send, bled out, etc. if they appear in Spanish.

**Comment by CreativeMD** [comment]
Fixed in the newest version! Thanks for reporting this issue, was a small mistake.
