### ISSUE TITLE
not all damage should allow revive

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [CreativeMD/PlayerRevive#48]
for example in my modpack if you walk through a stargate backwards you just get knocked out, thats not how stargates work. my solution to this would be a whitelist in the config for damage types that bypass the revive mechanic, so i could whitelist "death.attack.sgcraft:transient" and "death.attack.sgcraft:iris" then if the player took fatal damage from those it would kill them as normal

**Comment by CreativeMD** [comment]
Added a new config option for that to the config. Also added the damage types you mentioned to the default list. If you have more which should be added by default just let me know. Thank you very much for your suggestion!
