### ISSUE TITLE
bypassDamageSources function in the mod config not working

### ISSUE THREAD

**Issue by ghost** [CreativeMD/PlayerRevive#49]
In json file of configuration there is example for bypassDamageSources like "death.attack.sgcraft:transient"

In lang file of Minecraft you can find similar lines for vanilla damage sources. (screenshot: https://i.imgur.com/CAnYgWE.png)

I tried to add three lines:
- "death.attack.player"
- "death.attack.player.item"
- "death.attack.lava"

Every one of them do not change anything. I cant kill other player with hands, items or lava.

Json file is valid and was not reseted to default.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Sorry for not responding earlier. If this issue still persists just let me know!
