### ISSUE TITLE
lang file question

### ISSUE THREAD

**Issue by TUsama** [CreativeMD/PlayerRevive#50]
In the en.us.lang, third row
> death.attack.bledToDeath.player **"**=%s bled out

The interpunction **"** is in right place?
BTW, when I add zh_cn.lang into the mod file, both row 1 and 2 still show English, it seems that it cannot work? or just I did something wrong?

**Comment by CreativeMD** [comment]
Yeah that's a small typo and fixed in the newest version. Thanks for letting me know.
