### ISSUE TITLE
Incompatiblity with Vampirism

### ISSUE THREAD

**Issue by Taknax** [CreativeMD/PlayerRevive#54]
Their is a incompat with V. If u die it lags extremly and u got a crash. I think the problem is by the site of Vampirism and Teamlappen, becuase its only trigged by PlayerRevive and after deleting the issue gone, but maybe you know a solution.

[https://pastebin.com/cT92TAQX](url)

**Comment by CreativeMD** [comment]
No idea, I think you should rather contact the author of vampirism.

**Comment by Taknax** [comment]
Did almost, awaiting an answer. Ty for time!!!!

**Comment by Taknax** [comment]
In the new update the issue isnt solved wirh vampirism?

**Comment by CreativeMD** [comment]
Hopefully fixed in the newest version.
