### ISSUE TITLE
Ingame crash.

### ISSUE THREAD

**Issue by Taknax** [CreativeMD/PlayerRevive#57]
I have an issue. If i die i get ingame crashes with logs. I have vanillafix installed and its not shutting down the game. Everything its even working but i got spams of crashlogs. I rly love this mod and its essential for my modpack. I hope you can find the issue.

[https://pastebin.com/ie24R5mq](url)

**Comment by CreativeMD** [comment]
Oh completely forgot to upload the new version, it should be available in a few minutes. Thanks for reporting this issue!
