### ISSUE TITLE
"Player was killed by magic" only possible death message when more than one person is online.

### ISSUE THREAD

**Issue by ghost** [CreativeMD/PlayerRevive#58]
I have a server I rent out of a different location. When I log in with only one account, I get the correct death message every time. But as soon as I log into the server with a second account to test, the dead message ONLY changes to "killed by magic" regardless of the damage source.

Other issues include: No "Player is bleeding" message when someone goes down anymore, either.

**Comment by CreativeMD** [comment]
I could not reproduce this issue with just PlayerRevive installed, so it's probably an issue caused by another mod. I will rewrite PlayerRevive soon anyway, so I will close this issue for now.
