### ISSUE TITLE
Took no damage and unable to /kill to suicide.

### ISSUE THREAD

**Issue by ChiNoel-osu** [CreativeMD/PlayerRevive#59]
Similar to issue #40 except the server didn't crash and the server didn't say anything other than [Killed Player] when I try to /kill someone on both client and server console. People just can't die :(
/kill in single-player (LAN World) did work tho.
I tried deleting the mod and reinstalling the entire server. And I found out that after I delete Terra Firma Craft everything went back to normal.
But even with Terra Firma Craft being the only mod installed on the server, /kill still doesn't work. This looks really weird.
With TFC and PlayerRevive installed on a new server, I can take damage and die after giving up at the rescue screen. But once I issued command /kill I went into god mode and nothing can damage me. Reconnecting to the server or restarting the server didn't solve this.

sorry for the poor English since it's not my first language.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier, I will rewrite PlayerRevive completely and hope things will work then. I will close this issue for now as this won't be fixed for the old version.
