### ISSUE TITLE
First Aid cap issue

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/PlayerRevive#6]
ever since i updated both this mod and first aid that after revived by a player that i can not attack/hit any mobs or players untill i have die completely and respawn. also this is a known issue do not know who side it is for this is that when i do /revive as i am a op on my server to do some testing with this and first aid that the mobs dose not go after me (Have not try this with out first aid mod). so after the new bug and /revive i could not heal my self with a bandage (From First aid mod) and my part health dose not recover at all untill i respawn then it works.

https://github.com/ichttt/FirstAid/issues/18

**Comment by ichttt** [comment]
my bad
