### ISSUE TITLE
[v2.0.0-pre01] Game crashed during startup

### ISSUE THREAD

**Issue by Ritzumi** [CreativeMD/PlayerRevive#61]
**Description**
The game crashed during mod setup phase.

**How to reproduce**
1. Installed mods
2. Run the game
3. See error

**Version**
Forge: 36.1.25
Player Revive: v2.0.0-pre01
Creative Core: v2.1.3

**Attachments**
During test, only 2 mods were installed.
Log: https://gist.github.com/Ritzumi/7138a8f56e45dab64a6d66abb75713b0

Thank you.

**Comment by CreativeMD** [comment]
Forgot to upload a new version for CreativeCore. New version will be available very soon.
