### ISSUE TITLE
[v2.0.0-pre01]  /revive render player unable to use any item & No give up button

### ISSUE THREAD

**Issue by Ritzumi** [CreativeMD/PlayerRevive#62]
Description
Using /revive @p command persists the bleeding state which cause player unable to use any item or jump.
Also, while bleeding, there is no give up button.

How to reproduce

1. Join a new world
2. Open LAN to enable mod
3. Kill your character (see error)
4. Use /revive 
5. See error

Version
The test was conducted on Singleplayer + LAN mode
Forge: 36.1.25
Player Revive: v2.0.0-pre01
Creative Core: v2.2.0

Attachments
During test, only 2 mods were installed.
No any anomaly in log.
Image: https://imgur.com/a/EPeyHBC (Description in their respective captions)

Thank you.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
