### ISSUE TITLE
[v2.0.0-pre01] java.lang.Exception: Mod Loading has failed

### ISSUE THREAD

**Issue by zndrmn** [CreativeMD/PlayerRevive#63]
_Minecraft Version_: **1.16.5**
_Forge Version_: **1.16.5-forge-36.1.2**
_CreativeCore Version_: **v2.1.2** (_File Name_: "**CreativeCore_v2.1.2_mc1.16.5**")
_PlayerRevive Version_: **v2.0.0-pre01** (_File Name_: "**PlayerRevive_v2.0.0-pre01_mc1.16.5**")

_Latest Log File_: **https://gist.github.com/zndrmn/ea174d12ec48b20517cbe488fa57da49#file-latest-log**
_Crash Log File_: **https://gist.github.com/zndrmn/ff6802f6ece65a171ed9e9a4ff415f5c#file-crash-2021-06-06_04-00-06-fml-txt**

**Comment by Ritzumi** [comment]
Try update CreativeCore.
https://github.com/CreativeMD/PlayerRevive/issues/61

**Comment by CreativeMD** [comment]
Yep, update CreativeCore.
