### ISSUE TITLE
Skips bleedout timer upon healing (First Aid, 1.16.5)

### ISSUE THREAD

**Issue by cobaltw** [CreativeMD/PlayerRevive#68]
It seems like when you're healed by something like regen from a beacon, it instantly skips the bleed out timer and goes to the death screen. This occurs while using the First Aid mod, I haven't tested without it.
It also does not announce your death in chat, and while using the Gravestone mod, it does not place a grave where you died.

**Comment by CreativeMD** [comment]
Can you try it without First Aid, because I never had an issue like it?

**Comment by cobaltw** [comment]
After testing, it does seem to be caused by First Aid. Without it, even with regen your health won't go above 2 hearts while you're downed, but with First Aid your body continues to heal, and after a certain threshold it will cause the bleed timer to be skipped.
Not sure if it's something you could fix on your end, or if the First Aid author would have to fix it?

**Comment by CreativeMD** [comment]
Ask the author of First Aid and maybe link this issue here. I don't see a way to fix it from my end.

**Comment by CreativeMD** [comment]
Any news?

**Comment by CreativeMD** [comment]
I will close this issue for now. If you report it to the author of First Aid mention me in there (so I can join the conversation).
