### ISSUE TITLE
Dedicated Server Sometimes Indefinitely Stalls During Startup 

### ISSUE THREAD

**Issue by Mikeatron-User** [CreativeMD/PlayerRevive#69]
**Minecraft Version:** 1.16.5

**Mod Version:** v2.0.0-pre04

**Creative Core Version:** v2.2.1

**Modpack:** [Rising Civilizations](https://www.curseforge.com/minecraft/modpacks/rising-civilization)

**Description:**
This issue is extremely inconsistent and has a random chance of occurring. The server will freeze up during start up and simply stay there and do nothing. It does not detect it as a crash. You also cannot join the server. This issue only seems to be resolved by disabling PlayerRevive.

The log I have attached is what it looks like when the server freezes.
[logs_latest.log](https://github.com/CreativeMD/PlayerRevive/files/7148772/logs_latest.log)

**Comment by CreativeMD** [comment]
I have no idea to be honest. I can't find anything suspicious in the logs. Are you 100% sure it's related to PlayerRevive?

**Comment by TeamPeril** [comment]
> I have no idea to be honest. I can't find anything suspicious in the logs. Are you 100% sure it's related to PlayerRevive?

I obviously cant be 100% certain, but it stops happening whenever I remove PlayerRevive. If anything, ill do more testing and see what happens.

**Comment by CreativeMD** [comment]
Any news?

**Comment by Mikeatron-User** [comment]
> Any news?

No, I haven't quite had the time for testing. Ill update this issue when I have the time to test this.

**Comment by CreativeMD** [comment]
I will close this issue for now. Let me know here if there are any news.
