### ISSUE TITLE
Mod Version?

### ISSUE THREAD

**Issue by kenijey** [CreativeMD/PlayerRevive#7]
https://github.com/CreativeMD/PlayerRevive/blob/18b31079786b3b95867aadc1d41d1a032df55d42/src/main/java/com/creativemd/playerrevive/PlayerRevive.java#L51

**Comment by CreativeMD** [comment]
I don't think that's a big issue. I don't update these numbers every time i release a new version.

**Comment by kenijey** [comment]
ok so :D
