### ISSUE TITLE
config options "reviveItem" "needReviveItem" and "consumeReviveItem" are not working

### ISSUE THREAD

**Issue by DasMazl** [CreativeMD/PlayerRevive#71]
So, Im setting up a little private server for a hardcore project. The mod itself works fine. You die, can get revived etc. Also other config options like "bleedTime" or "healthAfterRevive" work perfectly. But the options "reviveItem", "needReviveItem" and "consumeReviveItem" just wont work. When I leave the item as default setting, which is on "minecraft:paper" and put "needReviveItem" on true, you can still revive others without having that item in your inventory.

```
"reviveItem": "{id:\"item\",item:\"minecraft:paper\"}",
"needReviveItem": true,
"consumeReviveItem": true,
```

The mod is running on 1.17.1 and the latest forge version

**Comment by CreativeMD** [comment]
This is just a placeholder, it's not actually implemented yet, sorry.
