### ISSUE TITLE
NuclearCraft: Overhauled radiation death persist [MineCraft 1.12.2]

### ISSUE THREAD

**Issue by ubergarm** [CreativeMD/PlayerRevive#73]
## Description
There seems to be some mod interactions between PlayerRevive and NuclearCraft:Overhauled with default configurations. When a player dies due to excessive radiation, it is possible to get stuck in a PlayerRevie "loop" that is difficult to escape. You can see an example in this [twitch stream video showing the glitch](https://www.twitch.tv/videos/1171415273?t=03h10m00s). Essentially before you can click "respawn" or "title screen" you end up in the PlayerRevive count-down again immediately and can't escape even with disconnect/reconnect.

To recreate this you have to have a multiplayer session and could use my modpack [Rotten Economy v0.90](https://www.curseforge.com/minecraft/modpacks/rotten-economy/files/3483967)

Thanks so much for PlayerRevive! It fits right into my modpack theme and adds more co-op strategy and increases the suspense after dying! haha :)

## Work Around

The safest solution for now is to change the config in `nuclearcraft.cfg` to disable persisting radiation levels like this:
```
# If enabled, players' radiation levels will persist on death.
B:radiation_death_persist=false
```

In addition, adding the `fatal_rads` line into `playerrevive.json` might help in some cases:
```
"bypassDamageSources": [
    "gorgon",
    "death.attack.sgcraft:transient",
    "death.attack.sgcraft:iris",
    "death.attack.fatal_rads"
]
```

My impression is that the [NuclearCraft: Overhauled Github onPlayerRespawn event](https://github.com/tomdodd4598/NuclearCraft/blob/1.12.2o/src/main/java/nc/handler/PlayerRespawnHandler.java#L40-L44) is maybe not triggering properly.  If that is the case, the "revive loop" glitch might occur say if a player has high radiation but the actual death.attack happens to be due to something else than fatal_rads. But I'm not sure how to test this hypothesis.

## Versions
* Forge `forge-1.12.2-14.23.5.2855.jar`
* PlayerRevive `PlayerRevive_v1.2.40_mc1.12.2.jar`
* [NuclearCraft: Overhauled](https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled) `NuclearCraft-2o.5.5-1.12.2.jar`
* [Rotten Economy Modpack v0.90 Source](https://github.com/ubergarm/RottenEconomy/tree/v0.90)

**Comment by CreativeMD** [comment]
Hey sorry for not responding earlier. First of all thank you for your detailed description of the issue. I'm just not sure how I could change anything. Might be a good idea to report this issue to NuclearCraft and post the link to this issue here. Maybe with the other author involved we can solve this issue together.

**Comment by CreativeMD** [comment]
Will close this issue for now. Doesn't look like it will be fixed. Sorry, I'm still there if the author replies.
