### ISSUE TITLE
Sometimes the player revive doesent occur

### ISSUE THREAD

**Issue by Mr-Syntax** [CreativeMD/PlayerRevive#75]
in this pack i made
https://www.curseforge.com/minecraft/modpacks/chosencraft

sometimes when i bleed out the player revive event doesent happen i just die straight up
is this whats suppose to happen or an incompatiblity?

sadly im actually unsure of what mod is causing the bleeding effect it was in one of the other mods i installed and i liked it so decided it could stay.... 

great mod btw love the music so fucking intense :D

**Comment by CreativeMD** [comment]
It's definitely an issue with another mod and I don't know which one. I know that PotionsCore can cause issues, but there are some others as well. I guess there is no other way than to try remove mods and see if it still occurs. Sorry can't do more for you :(

**Comment by CreativeMD** [comment]
Will close this issue for now. If there any news let me know here.
