### ISSUE TITLE
1.16.5 Doesn't Work (Literally Nothing Happens)

### ISSUE THREAD

**Issue by Figgmastah** [CreativeMD/PlayerRevive#76]
I use this mod on a 1.16.5 Modpack and when I die nothing happens, I play in Singleplayer tho. I Took a singleplayer world to LAN and still nothing happened but I have never tested it with other people. Does nothing happen when im on singleplayer and I need to play with others or what? I even tested the mod completely alone and it still didn't work! I use Forge Version 36.2.8

**Comment by CreativeMD** [comment]
This mod obviously doesn't work in singleplayer. It only works if you are on a server or if the singleplayer is opened to LAN.
