### ISSUE TITLE
Server crashes whenever someone dies

### ISSUE THREAD

**Issue by fausb** [CreativeMD/PlayerRevive#77]
Hi, in my 1.12.2 server and in my client I have PlayerRevive v1.2.40 installed, but when someone dies, the server crashes along with an error.
The server is hosted in aternos, and the forge version is 14.23.5.2859, I hope you can find the issue

**Comment by CreativeMD** [comment]
I don't support 1.12 anymore, if you want to you can still send me the crash-report, I might be able to tell what is happening.
