### ISSUE TITLE
Galacticraft Compatibility (Invisible Body)

### ISSUE THREAD

**Issue by kenijey** [CreativeMD/PlayerRevive#8]
playing on lan, using forge 2604 on mc 1.12.2, latest player revive on curse. [HERE ](https://github.com/kenijey/Ezteria)is my modpack if u need to test, but we could never see our dead bodies... please help :(

**Comment by CreativeMD** [comment]
Could you test if this happens if only PlayerRevive is installed?

**Comment by kenijey** [comment]
i did test it, i can see my second launcher's body (used usernamemod to join second player) but cant see my friend's body. should i try to find which mod causing it? :l

**Comment by CreativeMD** [comment]
That would be very very helpful.

**Comment by kenijey** [comment]
okay........... i found it after full time spent of an hour... it's galacticraft.
if you install GalacticraftCore-1.12.2-4.0.1.128, Galacticraft-Planets-1.12.2-4.0.1.128 and MicdoodleCore-1.12.2-4.0.1.128, you will not be able to see your friend's dead body. hope you find a fix for it, today we play with visible dead bodies i hope :D

**Comment by kenijey** [comment]
also used forge 2607

**Comment by CreativeMD** [comment]
I reported this issue to Galacticraft, hope we will be able to figure out a fix for this.
