### ISSUE TITLE
Mohist incopatability: Can't respawn before relogging

### ISSUE THREAD

**Issue by Toldoven** [CreativeMD/PlayerRevive#83]
I've already opened [an issue on Mohist GitHub](https://github.com/MohistMC/Mohist/issues/2069), but I just want to let other people know about this since I've wasted about 2 hours trying to figure out what was causing this problem. 

I'm not sure if it's fixable from the PlayerRevive side. Or if someone is willing to fix it. It seems like a lot of developers just don't want to do anything with Mohist, and I can understand it. 

--- 

**Minecraft Version :** 1.16.5

**Mohist Version :** Mohist version 1.16.5-954 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.26)

**Here is the video demonstrating the issue:** https://streamable.com/130o4u

Tested on a fresh install of Mohist with only PlayerRevive and CreativeCore mods installed. After you try to respawn, you will be killed again. Leaving and joining the server allows you to respawn.

**Server logs:** https://gist.github.com/KPidS/512823b7d7ce1fedb0dd5b2e76d56b75

**Client logs:** https://gist.github.com/KPidS/40a250baba0c112dc9f46d83622abc6e

**Comment by MagnusHJensen** [comment]
This issue needs to be contained within Mohist.
It has nothing to do with PlayerRevive, it's purely on mohist's side.
Please close the issue, the mod developer can't do anything.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. Like @MagnusHJensen I see no way to fix it from my end. Furthermore I don't support 1.16 anymore.
