### ISSUE TITLE
Revive Bug with Mr.Crayfish guns mod

### ISSUE THREAD

**Issue by Relap-O2** [CreativeMD/PlayerRevive#84]
Hello! I was trying to change on the config files the fact that you can actually shoot the guns while you're down, since i wasn't able to change this "bug" i would like to warn you that is possible to kill people while being down.

**Comment by CreativeMD** [comment]
Which version are you using? I need more information.

**Comment by Relap-O2** [comment]
Of course, sorry! "PlayerRevive_v2.0.0-pre08_mc1.18.1.jar" in the 1.18.1 version

**Comment by CreativeMD** [comment]
I have reported the issue to Mr. Crayfish. Unfortunately I cannot fix it from my end. Let's hope it will be fixed soon.
