### ISSUE TITLE
Can still interact with the world after being downed

### ISSUE THREAD

**Issue by Jetpack-Cat** [CreativeMD/PlayerRevive#86]
1.16.5 forge latest
I don't know if this is specific to using mr crayfish's gun mod, but when downed, if you hold left click to give up, it fires your gun and wont lower the give up 4 second timer, if I switch to an empty hand slot, then it just makes me punch but will start counting down to give up but you're punching the ground still interacting with the world

**Comment by CreativeMD** [comment]
This is a known issue and has been reported to the crayfish's gun mod already, but unfortunately I got no response so far. https://github.com/MrCrayfish/MrCrayfishGunMod/issues/285
