### ISSUE TITLE
[1.18.2]FirstAid linkage problem(FirstAid联动问题)

### ISSUE THREAD

**Issue by YongAn404** [CreativeMD/PlayerRevive#88]
After death, you can check that the blood volume has been restored through other auxiliary plug-ins, but the blood volume has not been updated in FirstAid, and you will die if you hit it with empty hands.
死亡后通过其他辅助插件可查询到血量已回复，但是在FirstAid中没有更新血量，空手打一下就死，以下是两个模组配置相关

![image](https://user-images.githubusercontent.com/101850798/171528170-c2fd52ed-0def-4fba-ad83-2d5ee5f5b347.png)

The following is the configuration of the two modules.
以下是两个模组配置相关
PlayerRevive
[playerrevive.json.txt](https://github.com/CreativeMD/PlayerRevive/files/8819834/playerrevive.json.txt)
FirstAid
[firstaid-common.toml.txt](https://github.com/CreativeMD/PlayerRevive/files/8819835/firstaid-common.toml.txt)
[firstaid-server.toml.txt](https://github.com/CreativeMD/PlayerRevive/files/8819836/firstaid-server.toml.txt)

**Comment by ichttt** [comment]
Just a heads-up, this is most likely an issue on my side, as the compat layer in FirstAid is not in for newer MC versions. See https://github.com/ichttt/FirstAid/issues/167

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. Is there anything I can do on my end? Yes I wanted to rewrite this mod when porting it, which took some time.

**Comment by CreativeMD** [comment]
Will close this issue for now as it cannot be fixed from my end.
