### ISSUE TITLE
Crashes If Press Enter While Reviving

### ISSUE THREAD

**Issue by kenijey** [CreativeMD/PlayerRevive#9]
if you press enter while reviving a dead player, it crashes.
[crash-2018-01-30_19.36.45-client.txt](https://github.com/CreativeMD/PlayerRevive/files/1678507/crash-2018-01-30_19.36.45-client.txt)

**Comment by CreativeMD** [comment]
I will upload a fix for it soon.

**Comment by kenijey** [comment]
how about the other issue? :D

**Comment by CreativeMD** [comment]
It is fixed now. Thanks for reporting this issue!
