### ISSUE TITLE
Items lost forever if used with Quark Oddities "Totem of Holding" (corpse system) under certain circumstance.

### ISSUE THREAD

**Issue by greanthai420** [CreativeMD/PlayerRevive#92]
If a player died then exit the game for any reason while still in the revivable state, the "corpse" will not show up.
So all items in their inventory will be lost forever.

**Comment by CreativeMD** [comment]
Once a player disconnects, PlayerRevive kills the player. So maybe contact the other author. I don't know how to fix it from my end.

**Comment by CreativeMD** [comment]
I will close this issue for now, because I don't think I can do anything about it. I highly recommend to report this issue to Quark Oddities. They might be able to help out. You can also send me the link of this issue here so I can join the conversation.

**Comment by greanthai420** [comment]
Hello, sorry for the delayed reply.
I have opened an issue at Quark's github here.

https://github.com/VazkiiMods/Quark/issues/3849
