### ISSUE TITLE
Still being able to attack when downed with Epic Fight mod

### ISSUE THREAD

**Issue by ricchix** [CreativeMD/PlayerRevive#95]
https://user-images.githubusercontent.com/89796563/180588043-3c0fa87a-4ded-449b-86d7-b8137e13f7b2.mp4

This is on 1.18.2 and Forge 40.1.68
PlayerRevive version: 2.0.1
EpicFight version: 18.2.6-beta

**Comment by CreativeMD** [comment]
Replied to their issue, will close this here for now as it cannot be fixed on my end: https://github.com/Yesssssman/epicfightmod/issues/1090

**Comment by ricchix** [comment]
Thanks!

**Comment by Sebaspc97** [comment]
> 

https://github.com/Yesssssman/epicfightmod/issues/1090#issuecomment-1193801238

**Comment by CreativeMD** [comment]
@Sebaspc97 yes?
