### ISSUE TITLE
BUG respawn

### ISSUE THREAD

**Issue by MiguVT** [CreativeMD/PlayerRevive#96]
Hello, i am using [v2.0.1 (1.18.2)](https://www.curseforge.com/minecraft/mc-mods/playerrevive/files/3759779) and i cant use it because when i respawn i die, in the server console and client logs.log and debug.log i dont get information, this is my config:

```json
{
  "banPlayerAfterDeath": false,
  "bleeding": {
    "bleedTime": 1200,
    "bleedingMessage": true,
    "bleedingMessageTrackingOnly": true,
    "shouldGlow": false,
    "hasBleedingMobEffect": true,
    "bleedingMobEffect": {
      "effect": "minecraft:slowness",
      "amplifier": 2,
      "duration": 10
    },
    "affectHunger": true,
    "remainingHunger": 6,
    "bleedingHealth": 10,
    "disableMobDamage": true,
    "disablePlayerDamage": false,
    "disableOtherDamage": false
  },
  "revive": {
    "requiredReviveProgress": 100.0,
    "progressPerPlayer": 1.0,
    "exhaustion": 0.5,
    "haltBleedTime": true,
    "abortOnDamage": false,
    "resetProgress": false,
    "hasRevivedMobEffect": false,
    "revivedMobEffect": {
      "effect": "minecraft:slowness",
      "amplifier": 2,
      "duration": 1
    },
    "reviveItem": "{id:\"item\",item:\"minecraft:paper\"}",
    "needReviveItem": false,
    "consumeReviveItem": false,
    "maxDistance": 3,
    "healthAfter": 2
  },
  "sounds": {
    "death": {
      "sound": "playerrevive:death",
      "volume": 1.0,
      "pitch": 1.0
    },
    "revived": {
      "sound": "playerrevive:revived",
      "volume": 1.0,
      "pitch": 1.0
    }
  },
  "bypassDamageSources": [
    "gorgon",
    "death.attack.sgcraft:transient",
    "death.attack.sgcraft:iris"
  ]
}
```

I try all the 1.18.2 version (3 versions) and the same.

My mods are: ChiselsBits-forge-1.18.2-1.2.113-universal, CreativeCore_FORGE_v2.6.12_mc1.18.2, elevatorid-1.18.2-1.8.4, ironchest-1.18.2-13.1.9, jei-1.18.2-9.7.0.209, journeymap-1.18.2-5.8.5-forge, Mantle-1.18.2-1.9.27, MoreVanillaArmor-1.18.2-3.1.2, PlayerRevive_FORGE_v2.0.1_mc1.18.2, TConstruct-1.18.2-3.5.1.31, trashslot-forge-1.18.1-11.0.2, TravelersBackpack-1.18.2-7.1.4 and voicechat-forge-1.18.2-2.2.52

Right now no plugins but i use magma.

Here is a video: https://youtu.be/fYW-5G3Sx2U

I try it with Java 18 and Java 17 if i use less my server crash

If you need something tell me (Server log, or other thing)

It works nice when
- I go to the main menu
- Someone revive me (When i dont die)

As you can view in the video i dont die when i go to main menu and it isnt only fall damage

**Comment by CreativeMD** [comment]
Magma and mohist seem to cause this issue, unfortunately there is nothing I can do about it from my end. Sorry.

**Comment by MiguVT** [comment]
No problem, you suggest me solicity help in magma?

**Comment by CreativeMD** [comment]
Yeah you should rather contact magma and/ or mohist, because I can't fix it.
