### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Djsergii25** [CreativeMD/PlayerRevive#98]
Hello Creative, when I install the mod and enter maincraft it crashes me and tells me that the mod cannot be put
I'm on version 1.16.5
the problem comes from the creative core mod that crashes my aternos server

**Comment by CreativeMD** [comment]
I need the crash-report in order to help you out.

**Comment by Djsergii25** [comment]
I don't have now, when i have i send you

**Comment by CreativeMD** [comment]
Ok, I will close the issue for now.
