### ISSUE TITLE
Revive doesn't work 1.18.2

### ISSUE THREAD

**Issue by Kene0Kn** [CreativeMD/PlayerRevive#99]
Hello here is my issue

when a player bleeds i can right click on his body but when i get to 100% he dies

I don't know if it's a compatibility error

I have some mods installed but I don't know if they are compatible with player revive

**Comment by CreativeMD** [comment]
Are you using mohist? Also can you give me a list of all your mods installed. Best way to do so is to send me the latest.log (you can upload it to pastebin or similar websites and post the link here).

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists send the log file here.
